### DISCUSSION TITLE
Unable to add meter for rate-limiting packets

### DISCUSSION THREAD

**Discussion by Yawndy** [faucetsdn/faucet#3969] [Q&A]
I am trying to add a meter so I can implement rate-limiting for my Faucet SDN solution, but I always get this error when running check_faucet_config, "AttributeError: 'str' object has no attribute 'get'".

Here is my current config:
```

meters:
        block-dos:
                meter_id: 100
                entry:
                        flags: PKTPS
                        bands:
                                rate: 1
```

Is anybody able to tell me what I'm doing wrong here? Any help is GREATLY appreciated!
