### ISSUE TITLE
Gauge creates a of_port stats metric with port_name="None"

### ISSUE THREAD

**Issue by gizmoguy** [faucetsdn/faucet#1089]
If you give faucet/gauge a configuration with a valid DP but an interface that doesn't exist like so:

```
version: 2
vlans:
    100:
        name: "office"
dps:
    sw1:
        dp_id: 0x1
        hardware: "Open vSwitch"
        interfaces:
            100:
                native_vlan: 100
```

Where let's say sw1 (dpid 0x1) has a single port with of_port=1.

You will get metrics with the port_name label set to None and statistics:

Element | Value
-- | --
of_port_rx_bytes{dp_id="0x1",instance="gauge:9303",job="gauge",port_name="None"} | 3008
