### ISSUE TITLE
If a DP has an empty interfaces array in faucet.yaml then faucet will crash

### ISSUE THREAD

**Issue by gizmoguy** [faucetsdn/faucet#1090]
If you provide the following config to faucet:

```
version: 2
vlans:
    100:
        name: "office"
dps:
    sw1:
        dp_id: 0x1
        hardware: "Open vSwitch"
        interfaces:
```

You will generate a crash:

> Traceback (most recent call last):
>   File "/usr/lib/python3.6/site-packages/faucet/valve_util.py", line 34, in __koe
>     func(*args, **kwargs)
>   File "/usr/lib/python3.6/site-packages/faucet/faucet.py", line 163, in _load_configs
>     new_config_file, self.logname)
>   File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 60, in dp_parser
>     config_hashes, dps = _config_parser_v2(config_file, logname)
>   File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 176, in _config_parser_v2
>     top_confs['vlans'])
>   File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 138, in _dp_parser_v2
>     _dp_add_ports(dp, dp_conf, dp_id, vlans)
>   File "/usr/lib/python3.6/site-packages/faucet/config_parser.py", line 116, in _dp_add_ports
>     for port_num, port_conf in list(ports_conf.items()):
> AttributeError: 'NoneType' object has no attribute 'items'
