### ISSUE TITLE
InterVLAN Routing should error when a specified VLAN doesn't exist

### ISSUE THREAD

**Issue by gizmoguy** [faucetsdn/faucet#1105]
This configuration should produce an error:

```
version: 2
routers:
    router-1:
        vlans: [100, 300]
vlans:
    100:
        description: "office1"
    200:
        description: "office2"
dps:
    sw1:
        dp_id: 0x1
        hardware: "Open vSwitch"
        interfaces:
            1:
                name:  blah
                native_vlan: 100
            2:
                name:  blah
                native_vlan: 200
```
