### ISSUE TITLE
Take more care when allowing the user to override elements in faucet.yaml

### ISSUE THREAD

**Issue by gizmoguy** [faucetsdn/faucet#1107]
Currently you can override whatever you want in the parsed faucet.yaml dict:

```
vlans:
    100:
         name: "office1"
dps:
    sw1:
        dp_id: 0x1
        hardware: "Open vSwitch"
        interfaces:
            1:
                name:  blah
                native_vlan: 100
```

This configuration will actually make a VLAN called "office1" and interface named "blah" despite the keys being "100" and "1". Now this can be quite handy for renaming ports without having to define the ofport and renaming VLANs without having to define the vid explicitly.

However it makes it very easy to shoot yourself in the foot. i.e some configuration elements such as the "routing" element can only refer to a name and not to key/name.
