### ISSUE TITLE
Need a shorthand -  dps: all in gauge.yaml

### ISSUE THREAD

**Issue by shivarammysore** [faucetsdn/faucet#1164]
In gauge.yaml, we have dps for watcher configured as:

```
 port_status_poller:
       type: 'port_state'
       dps: ['ovs-qotom-allbirds-1', 'switch2']
       db: 'influx'
```
can we have an option such as:

```
dps: all
```
which indicates that all the dps in faucet.yaml must be added to this watcher.
