### ISSUE TITLE
Crash when mirror port doesn't exist

### ISSUE THREAD

**Issue by gizmoguy** [faucetsdn/faucet#1269]
So using the following configuration, since we don't have a port named "dag" on this DP we will crash because the mirror port isn't resolvable.

```
dps:
    at-x930-1:
        dp_id: 0xeccd6df7d4aa
        description: "at-x930-1"
        hardware: "Allied-Telesis"
        interfaces:
            1:
                name: "port1.0.1"
                native_vlan: redcables
                acl_in: mirror_all
acls:
    # ACL rule for inspecting all traffic
    mirror_all:
        - rule:
            actions:
                mirror: dag
                allow: 1
```

> Traceback (most recent call last):
>   File "/usr/local/lib/python3.5/dist-packages/faucet/valve_util.py", line 34, in __koe
>     func(*args, **kwargs)
>   File "/usr/local/lib/python3.5/dist-packages/faucet/faucet.py", line 232, in _send_flow_msgs
>     ryu_dp.send_msg(flow_msg)
>   File "/usr/local/lib/python3.5/dist-packages/ryu/controller/controller.py", line 408, in send_msg
>     msg.serialize()
>   File "/usr/local/lib/python3.5/dist-packages/ryu/ofproto/ofproto_parser.py", line 270, in serialize
>     self._serialize_body()
>   File "/usr/local/lib/python3.5/dist-packages/ryu/ofproto/ofproto_v1_3_parser.py", line 2712, in _serialize_body
>     inst.serialize(self.buf, offset)
>   File "/usr/local/lib/python3.5/dist-packages/ryu/ofproto/ofproto_v1_3_parser.py", line 2901, in serialize
>     a.serialize(buf, action_offset)
>   File "/usr/local/lib/python3.5/dist-packages/ryu/ofproto/ofproto_v1_3_parser.py", line 3010, in serialize
>     offset, self.type, self.len, self.port, self.max_len)
>   File "/usr/local/lib/python3.5/dist-packages/ryu/lib/pack_utils.py", line 25, in msg_pack_into
>     struct.pack_into(fmt, buf, offset, *args)
> struct.error: required argument is not an integer
