### ISSUE TITLE
stacking loop occurs if vlan is enabled on stack ports.

### ISSUE THREAD

**Issue by trungdtbk** [faucetsdn/faucet#1274]
To reproduce:
```
dps:
    l3-sw1:
        dp_id: 0x1
        stack:
            priority: 1
        interfaces:
            1:
                tagged_vlans: [l3-100]
                stack:
                    dp: l2-sw1
                    port: 1
            2:
                tagged_vlans: [l3-100]
                stack:
                    dp: l2-sw2
                    port: 1
            3:
                native_vlan: l3-200
    l2-sw1:
        dp_id: 0x2
        interfaces:
            1:
                stack:
                    dp: l3-sw1
                    port: 1
            2:
                stack:
                    dp: l2-sw2
                    port: 2
            3:
                native_vlan: l2-100
    l2-sw2:
        dp_id: 0x3
        interfaces:
            1:
                tagged_vlans: [l2-100]
                stack:
                    dp: l3-sw1
                    port: 2
            2:
                stack:
                    dp: l2-sw1
                    port: 2
            3:
                native_vlan: l2-100
routers:
    router-1: 
        vlans: [l3-100, l3-200]
vlans:
    l3-100:
        vid: 100
    l3-200:
        vid: 200
    l2-100:
        vid: 100
```
