### ISSUE TITLE
Unhandled exception when stacking with missing vlan config

### ISSUE THREAD

**Issue by trungdtbk** [faucetsdn/faucet#1275]
to reproduce:
```
dps:
    l3-sw1:
        dp_id: 0x1
        stack:
            priority: 1
        interfaces:
            1:
                stack:
                    dp: l3-sw2
                    port: 1
            2:
                stack:
                    dp: l2-sw1
                    port: 1
            3:
                native_vlan: l3-200
    l3-sw2:
        dp_id: 0x2
        interfaces:
            1:
                stack:
                    dp: l3-sw1
                    port: 1
            2:
                stack:
                    dp: l2-sw2
                    port: 1
            3:
                native_vlan: l3-200
    l2-sw1:
        dp_id: 0x3
        drop_spoofed_faucet_mac: False
        interfaces:
            1:
                stack:
                    dp: l3-sw1
                    port: 2
            2:
                native_vlan: l2-100
    l2-sw2:
        dp_id: 0x04
        drop_spoofed_faucet_mac: False
        interfaces:
            1:
                stack:
                    dp: l3-sw2
                    port: 2
            2:
                native_vlan: l2-100
vlans:
    l3-200:
        vid: 200
    l2-100:
        vid: 100
```
Nov 27 02:53:37 faucet.exception ERROR    Unhandled exception, killing RYU
Traceback (most recent call last):
  File "/faucet/faucet/valve_util.py", line 34, in __koe
    func(*args, **kwargs)
  File "/faucet/faucet.py", line 417, in packet_in_handler
    flowmods = valve.rcv_packet(other_valves, pkt_meta)
  File "/faucet/faucet/valve.py", line 774, in rcv_packet
    ofmsgs.extend(self._learn_host(other_valves, pkt_meta))
  File "/faucet/faucet/valve.py", line 642, in _learn_host
    other_valves, pkt_meta)
  File "/faucet/faucet/valve_flood.py", line 363, in edge_learn_port
    edge_dp = self._edge_dp_for_host(other_valves, pkt_meta)
  File "/faucet/faucet/valve_flood.py", line 344, in _edge_dp_for_host
    other_dp_host_cache = other_valve.dp.vlans[vlan_vid].host_cache
KeyError: 200
I will make a fix for this.
