### ISSUE TITLE
IP packets to get broadcast when dst rules timeout.

### ISSUE THREAD

**Issue by trungdtbk** [faucetsdn/faucet#1277]
We have this simple topology.
```
(1.0.0.1) H1 (10.0.0.1) --- S1 --- (10.0.0.2) H2 (2.0.0.1)
```
Routing is enabled on S1. If no pkt destined to e.g. H1 for some time, its dst rule gets flushed. Then if H2 pings to 1.0.0.1, all packets will be broadcast. H1 replies to 2.0.0.1 with dst_mac = FAUCET_MAC. And Faucet can never learn H1 again as those packets hit only rule  dl_dst=[FAUCET_MAC], util H1 sends pkt with dst MAC != [FAUCET_MAC].

**Comment by anarkiwi** [comment]
Would you be able to attach configs please  - we're having some trouble understanding the problem.

**Comment by anarkiwi** [comment]
After some discussion we are guessing that you have long or static ARP entries on H1, and H1 and H2 are on the same VLAN (but routing via FAUCET) - which would be an unusual configuration. In any case if you can attach the FAUCET config and clarify what ARP timers are set to on H1 in particular that'd help.

**Comment by trungdtbk** [comment]
It can be reproduced as follow:
```
dps:
    l3-sw:
        dp_id: 0x1
        timeout: 120
        interfaces:
            1:
                native_vlan: l3-100
            2:
                native_vlan: l3-100
            3:
                native_vlan: l3-100
            4:
                native_vlan: l3-100
vlans:
    l3-100:
        vid: 100
        faucet_vips: ['10.0.0.254/24']
        routes:
            - route:
                ip_dst: 1.0.0.0/24
                ip_gw: 10.0.0.1
            - route:
                ip_dst: 2.0.0.0/24
                ip_gw: 10.0.0.2
            - route:
                ip_dst: 3.0.0.0/24
                ip_gw: 10.0.0.3
```
H1,2,3,4 default gw to 10.0.0.254.
1. H1 ping 2.0.0.1
2. Stop ping. wait 120s, all src, dst rules disappear.
3. H1 ping 2.0.0.1
4. packets are broadcast as no dst rules for H2.
