### ISSUE TITLE
Tagged VLAN gets tag stripped off in eth_dst table.

### ISSUE THREAD

**Issue by Bairdo** [faucetsdn/faucet#1499]
I've got a bug that I'm not sure how to reproduce easily and so far have been unable to make a test case. (can reproduce in an non automated way)

When using taggedvlans there is a bug that installs rules on the eth_dst table stripping off the tagged VLAN, and outputting, when it should include the VLAN tag.

e.g
```
duration=181.259s, table=7, n_packets=11, n_bytes=1232, idle_timeout=295, idle_age=45, priority=9099,dl_vlan=300,dl_dst=b8:27:eb:c9:d1:43 actions=strip_vlan,output:1
```

From the packet capture of the Openflow connection it looks like a packet in is received for a MAC not in the eth_src table. Entry in table eth_dst is then deleted for corresponding MAC and VLAN (tagged) on both eth_src & eth_dst tables.  2 Rules are then added for eth_src & eth_dst, however the eth_dst rule has the strip vlan

Attached below is a capture of the control plane.

Packet 305 (openflow_v4.xid == 2637212484) shows the flow being added.

Packet 300 (openflow_v4.xid == 2637212487) has a delete on table 7 matching the tagged vlan and the dst mac (b8:27:eb:c9:d1:43).

Packet 297 (openflow_v4.packet_in.buffer_id == 272) has a packet in with the src mac b8:27:eb:c9:d1:43

Config:
```yaml
version: 2
vlans:
    100:
dps:
    faucet-1:
        dp_id: 0xacd25cd01
        hardware: "Open vSwitch"
        interfaces:
            1:
                native_vlan: 100
                acl_in: port_faucet-1_2
                tagged_vlans: [200, 300]

            3:
                native_vlan: 100
            4:
                native_vlan: 100
                tagged_vlans: [200, 300]
include:
    - /etc/ryu/faucet/faucet-acls.yaml
```
Sorry the clock on the switch was faster by 1minute 2s. (Ill redo the captures on Monday from the same machine.)

[faucet.log](https://github.com/faucetsdn/faucet/files/1624905/faucet.log)

[openflow.pcap.zip](https://github.com/faucetsdn/faucet/files/1624883/openflow.pcap.zip)
