### ISSUE TITLE
Ignoring non-physical ports breaks use of OFPP_LOCAL

### ISSUE THREAD

**Issue by simeonmiteff** [faucetsdn/faucet#1511]
I've previously used the local port (0xfffffffe) for convenience in-band access to my DP control plane. 

Rejecting configuration of ports with `ignore_port()` now prevents the use of local with FAUCET (technically also OFPP_NORMAL, but I am less interested in that).

Can we maybe just allow OFPP_LOCAL?

**Comment by anarkiwi** [comment]
Can you share your config?

**Comment by simeonmiteff** [comment]
```
vlans:
    2:
        name: "home network"
dps:
    homeswitch:
        dp_id: 0x1
        hardware: "Allied-Telesis"
        interfaces:
            1:
                native_vlan: 2
#<snip>
            10:
                native_vlan: 2
            0xfffffffe:
                native_vlan: 2
                description: "homeswitch local port"
```
