### ISSUE TITLE
config validation fails when meters are present

### ISSUE THREAD

**Issue by trentindav** [faucetsdn/faucet#1549]
I noticed errors when running regression tests against hardware switches (and Faucet release 1.6.18) which support meters: the error is triggered when validating the ACL configuration because the meter is received as a string instead of dictionary.

The following is the content of `FaucetUntaggedApplyMeterTest-test_untagged/faucet.log`
```
Jan 22 19:30:12 faucet ERROR    New config bad (meter value lossymeter must be <class 'dict'> not <class 'str'>) - rejecting
Jan 22 19:30:12 faucet ERROR    features_handler: unknown datapath DPID 1 (0x1)
....
```
This test is using this configuration:
```yaml
meters:
    lossymeter:
        meter_id: 1
        entry:
            flags: "KBPS"
            bands:
                [
                    {
                        type: "DROP",
                        rate: 1000
                    }
                ]
acls:
    lossyacl:
        - rule:
            actions:
                meter: lossymeter
                allow: 1
```
