### ISSUE TITLE
IVR reloads are not safe when one of the member vlans change VIDs

### ISSUE THREAD

**Issue by gizmoguy** [faucetsdn/faucet#1608]
If we say have this config:

```
vlans:
    v2314:
        vid: 2314
        faucet_mac: 'aa:bb:cc:dd:23:14'
        faucet_vips: ['1.1.1.1/24']
    v1100:
        vid: 1100
        faucet_mac: 'aa:bb:cc:dd:11:00'
        faucet_vips: ['2.2.2.2/24']

routers:
    router-internet-conference:
        vlans: ['v2314', 'v1100']
dps:
    br-test:
        dp_id: 0x1
        interfaces:
            1:
                tagged_vlans: ['v2314']
            4:
                native_vlan: 'v1100'
```

And change all references of 1100 to 1101, and perform a faucet reload.

If we diff the flow table after we perform the reload:

```
--- vlan1100-config.flows     2018-02-03 22:27:23.184884205 +1300
+++ vlan1101-config.flows  2018-02-03 22:27:48.829478577 +1300
@@ -8 +8 @@
- table=1, priority=9000,in_port=2,vlan_tci=0x0000/0x1fff actions=push_vlan:0x8100,set_field:5196->vlan_vid,goto_table:3
+ table=1, priority=9000,in_port=2,vlan_tci=0x0000/0x1fff actions=push_vlan:0x8100,set_field:5197->vlan_vid,goto_table:3
@@ -12 +12 @@
- table=3, priority=9131,arp,dl_vlan=1100 actions=goto_table:6
+ table=3, priority=9131,arp,dl_vlan=1101 actions=goto_table:6
@@ -17 +17 @@
- table=3, priority=9099,ip,dl_vlan=1100,dl_dst=aa:bb:cc:dd:11:00 actions=goto_table:4
+ table=3, priority=9099,ip,dl_vlan=1101,dl_dst=aa:bb:cc:dd:11:00 actions=goto_table:4
@@ -21 +21 @@
- table=4, priority=9131,ip,dl_vlan=1100,nw_dst=2.2.2.2 actions=goto_table:6
+ table=4, priority=9131,ip,dl_vlan=1101,nw_dst=2.2.2.2 actions=goto_table:6
@@ -24,2 +24 @@
- table=4, priority=9123,ip,dl_vlan=2314,nw_dst=2.2.2.0/24 actions=goto_table:6
- table=4, priority=9123,ip,dl_vlan=1100,nw_dst=2.2.2.0/24 actions=goto_table:6
+ table=4, priority=9123,ip,dl_vlan=1101,nw_dst=2.2.2.0/24 actions=goto_table:6
@@ -37 +36 @@
- table=8, priority=9008,in_port=2,dl_vlan=1100,dl_dst=ff:ff:ff:ff:ff:ff actions=pop_vlan
+ table=8, priority=9008,in_port=2,dl_vlan=1101,dl_dst=ff:ff:ff:ff:ff:ff actions=pop_vlan
@@ -39 +38 @@
- table=8, priority=9006,in_port=2,dl_vlan=1100,dl_dst=33:33:00:00:00:00/ff:ff:00:00:00:00 actions=pop_vlan
+ table=8, priority=9006,in_port=2,dl_vlan=1101,dl_dst=33:33:00:00:00:00/ff:ff:00:00:00:00 actions=pop_vlan
@@ -42,2 +41,2 @@
- table=8, priority=9002,in_port=2,dl_vlan=1100,dl_dst=01:80:c2:00:00:00/ff:ff:ff:00:00:00 actions=pop_vlan
- table=8, priority=9004,in_port=2,dl_vlan=1100,dl_dst=01:00:5e:00:00:00/ff:ff:ff:00:00:00 actions=pop_vlan
+ table=8, priority=9002,in_port=2,dl_vlan=1101,dl_dst=01:80:c2:00:00:00/ff:ff:ff:00:00:00 actions=pop_vlan
+ table=8, priority=9004,in_port=2,dl_vlan=1101,dl_dst=01:00:5e:00:00:00/ff:ff:ff:00:00:00 actions=pop_vlan
@@ -45 +44 @@
- table=8, priority=9000,in_port=2,dl_vlan=1100 actions=pop_vlan
+ table=8, priority=9000,in_port=2,dl_vlan=1101 actions=pop_vlan
```

We will notice that mostly everything looks good (a number of rules change with the new VID), however a crucial IVR flow rule is not recreated:

`- table=4, priority=9123,ip,dl_vlan=2314,nw_dst=2.2.2.0/24 actions=goto_table:6`
