### ISSUE TITLE
When a port is modified that has BGP enabled change detector will always cold start DP

### ISSUE THREAD

**Issue by gizmoguy** [faucetsdn/faucet#1609]
Take this example config:

```
vlans:
    l3:
        vid: 100
        faucet_mac: "0e:00:00:00:24:06"
        faucet_vips: [
            '1.1.1.1/24'
            ]
        bgp_port: 9179
        bgp_as: 65000
        bgp_routerid: '127.0.0.2'
        bgp_neighbor_addresses: ['127.0.0.1', '::1']
        bgp_neighbor_as: 65000
    v10:
        vid: 10
    v11:
        vid: 11
dps:
    ovs-redcables:
        dp_id: 0x1
        hardware: "Open vSwitch"
        interfaces:
            1:
                tagged_vlans: [l3]
            2:
                native_vlan: v10
```

If change the vlan on port 2 to v11 and SIGHUP we will see faucet cold start the DP even though it correctly decided it could do a warm start:

> Feb 03 23:04:21 faucet INFO     request to reload configuration
> Feb 03 23:04:21 faucet INFO     configuration /etc/ryu/faucet/faucet.yaml changed, analyzing differences
> Feb 03 23:04:21 faucet.valve INFO     DPID 1 (0x1) VLAN 11 added
> Feb 03 23:04:21 faucet.valve INFO     DPID 1 (0x1) VLANs deleted: {10}
> Feb 03 23:04:21 faucet.valve INFO     DPID 1 (0x1) Delete VLAN VLAN v10 vid:10 ports:Port 2
> Feb 03 23:04:21 faucet.valve INFO     DPID 1 (0x1) ports changed/added: {2}
> Feb 03 23:04:21 faucet.valve INFO     DPID 1 (0x1) Port 2 down
> Feb 03 23:04:21 faucet.valve INFO     DPID 1 (0x1) VLANs changed/added: {11}
> Feb 03 23:04:21 faucet.valve INFO     DPID 1 (0x1) Delete VLAN VLAN v11 vid:11 ports:Port 2
> Feb 03 23:04:21 faucet.valve INFO     DPID 1 (0x1) Configuring VLAN v11 vid:11 ports:Port 2
> Feb 03 23:04:21 faucet.valve INFO     DPID 1 (0x1) Port 2 up
> Feb 03 23:04:21 faucet INFO     Warm starting DPID 1 (0x1)
> Feb 03 23:04:24 faucet INFO     Add new datapath DPID 1 (0x1)
> Feb 03 23:04:25 faucet INFO     DPID 1 (0x1) connected
> Feb 03 23:04:25 faucet.valve INFO     DPID 1 (0x1) Cold start configuring DP
> Feb 03 23:04:25 faucet.valve INFO     DPID 1 (0x1) Configuring VLAN l3 vid:100 ports:Port 1
> Feb 03 23:04:25 faucet.valve INFO     DPID 1 (0x1) Configuring VLAN v11 vid:11 ports:Port 2
> Feb 03 23:04:25 faucet.valve INFO     DPID 1 (0x1) Port 1 configured
> Feb 03 23:04:25 faucet.valve INFO     DPID 1 (0x1) Port 2 configured

If there was never any BGP configuration on vlan l3 then the faucet reload happens cleanly without a cold start.
