### ISSUE TITLE
When BGP is deconfigured from a VLAN and faucet reloaded a crash will occur on next reload 

### ISSUE THREAD

**Issue by gizmoguy** [faucetsdn/faucet#1610]
Take this example config:

```
vlans:
    l3:
        vid: 100
        faucet_mac: "0e:00:00:00:24:06"
        faucet_vips: [
            '1.1.1.1/24'
            ]
        bgp_port: 9179
        bgp_as: 65000
        bgp_routerid: '127.0.0.2'
        bgp_neighbor_addresses: ['127.0.0.1', '::1']
        bgp_neighbor_as: 65000
    v10:
        vid: 10
    v11:
        vid: 11
dps:
    ovs-redcables:
        dp_id: 0x1
        hardware: "Open vSwitch"
        interfaces:
            1:
                tagged_vlans: [l3]
            2:
                native_vlan: v10
            3:
                native_vlan: v11
```

If we remove all of the BGP configuration from the l3 vlan and do a faucet reload, initially all looks fine:

> Feb 03 23:25:24 faucet INFO     request to reload configuration
> Feb 03 23:25:24 faucet INFO     configuration /etc/ryu/faucet/faucet.yaml changed, analyzing differences
> Feb 03 23:25:24 faucet.valve INFO     DPID 1 (0x1) VLAN 100 config changed
> Feb 03 23:25:24 faucet.valve INFO     DPID 1 (0x1) ports changed/added: {1}
> Feb 03 23:25:24 faucet.valve INFO     DPID 1 (0x1) Port 1 down
> Feb 03 23:25:24 faucet.valve INFO     DPID 1 (0x1) VLANs changed/added: {100}
> Feb 03 23:25:24 faucet.valve INFO     DPID 1 (0x1) Delete VLAN VLAN l3 vid:100 ports:Port 1
> Feb 03 23:25:24 faucet.valve INFO     DPID 1 (0x1) Configuring VLAN l3 vid:100 ports:Port 1
> Feb 03 23:25:24 faucet.valve INFO     DPID 1 (0x1) Port 1 up
> Feb 03 23:25:24 faucet INFO     Warm starting DPID 1 (0x1)

However if we make a further change to the config, say change the vlan on port 2 to v11 instead of v10 we will see a crash:

> Feb 03 23:25:32 faucet INFO     request to reload configuration
> Feb 03 23:25:32 faucet INFO     configuration /etc/ryu/faucet/faucet.yaml changed, analyzing differences
> Feb 03 23:25:32 faucet.valve INFO     DPID 1 (0x1) VLAN 11 config changed
> Feb 03 23:25:32 faucet.valve INFO     DPID 1 (0x1) VLANs deleted: {10}
> Feb 03 23:25:32 faucet.valve INFO     DPID 1 (0x1) Delete VLAN VLAN v10 vid:10 ports:Port 2
> Feb 03 23:25:32 faucet.valve INFO     DPID 1 (0x1) ports changed/added: {2, 3}
> Feb 03 23:25:32 faucet.valve INFO     DPID 1 (0x1) Port 2 down
> Feb 03 23:25:32 faucet.valve INFO     DPID 1 (0x1) Port 3 down
> Feb 03 23:25:32 faucet.valve INFO     DPID 1 (0x1) VLANs changed/added: {11}
> Feb 03 23:25:32 faucet.valve INFO     DPID 1 (0x1) Delete VLAN VLAN v11 vid:11 ports:Port 2,Port 3
> Feb 03 23:25:32 faucet.valve INFO     DPID 1 (0x1) Configuring VLAN v11 vid:11 ports:Port 2,Port 3
> Feb 03 23:25:32 faucet.valve INFO     DPID 1 (0x1) Port 2 up
> Feb 03 23:25:32 faucet.valve INFO     DPID 1 (0x1) Port 3 up
> Feb 03 23:25:32 faucet INFO     Warm starting DPID 1 (0x1)
> Feb 03 23:25:32 faucet.exception ERROR    Unhandled exception, killing RYU
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/site-packages/faucet/valve_util.py", line 34, in __koe
>     func(*args, **kwargs)
>   File "/usr/lib/python3.6/site-packages/faucet/faucet.py", line 225, in _load_configs
>     self._apply_configs(new_dps)
>   File "/usr/lib/python3.6/site-packages/faucet/faucet.py", line 217, in _apply_configs
>     self._bgp.reset(self.valves, self.metrics)
>   File "/usr/lib/python3.6/site-packages/faucet/faucet_bgp.py", line 116, in reset
>     bgp_speaker.shutdown()
>   File "/usr/lib/python3.6/site-packages/ryu/services/protocols/bgp/bgpspeaker.py", line 383, in shutdown
>     call('core.stop')
>   File "/usr/lib/python3.6/site-packages/ryu/services/protocols/bgp/api/base.py", line 212, in call
>     raise r
>   File "/usr/lib/python3.6/site-packages/ryu/services/protocols/bgp/api/base.py", line 209, in call
>     return call(**kwargs)
>   File "/usr/lib/python3.6/site-packages/ryu/services/protocols/bgp/api/core.py", line 57, in stop
>     raise RuntimeConfigError('No runtime is active. Call start to create '
> ryu.services.protocols.bgp.rtconf.base.RuntimeConfigError: 200.1 - No runtime is active. Call start to create a runtime
