### ISSUE TITLE
group error with multiple DPs and nailed forwarding

### ISSUE THREAD

**Issue by anarkiwi** [faucetsdn/faucet#1752]
```
vlans:
   tousix:
     vid: 100
     description: "IXP_VLAN"
dps:
   Edge1:
     dp_id: 0x1
     hardware: "Allied-Telesis"
     interfaces:
       1:
         name: "h1"
         description: "h1"
         native_vlan: 100
         acl_in: 1
       25:
         name: "link"
         description: "link"
         native_vlan: 100
         acl_in: 1
         opstatus_reconf: False
       28:
         name: "link"
         description: "link"
         native_vlan: 100
         acl_in: 1
         opstatus_reconf: False
   Edge2:
     dp_id: 0x2
     hardware: "Allied-Telesis"
     interfaces:
       1:
         name: "h2"
         description: "h2"
         native_vlan: 100
         acl_in: 2
       25:
         name: link
         description: link
         native_vlan: 100
         acl_in: 2
         opstatus_reconf: False
       26:
         name: link
         description: link
         native_vlan: 100
         acl_in: 2
         opstatus_reconf: False
   Edge3:
     dp_id: 0x3
     hardware: "Allied-Telesis"
     interfaces:
       1:
         name: "h3"
         description: "h3"
         native_vlan: 100
         acl_in: 3
       28:
         name: "link"
         description: "link"
         native_vlan: 100
         acl_in: 3
         opstatus_reconf: False
       25:
         name: "link"
         description: "link"
         native_vlan: 100
         acl_in: 3
         opstatus_reconf: False
acls:
   1:
     - rule:
         dl_dst: "a0:36:9f:10:67:fc"
         actions:
           output:
             port: 1
     - rule:
         dl_type: 0x86DD
         ip_proto: 58
         icmpv6_type: 135
         ipv6_nd_target: "2001:7f8:68::1"
         actions:
           output:
             port: 1
     - rule:
         dl_type: 0x806
         dl_dst: "ff:ff:ff:ff:ff:ff"
         arp_tpa: "10.0.0.1"
         actions:
           output:
             port: 1
     - rule:
         dl_dst: "a0:36:9f:10:67:fd"
         actions:
           output:
             failover:
               group_id: 601
               ports: [25, 28]
     - rule:
         dl_type: 0x86DD
         ip_proto: 58
         icmpv6_type: 135
         ipv6_nd_target: "2001:7f8:68::2"
         actions:
           output:
             failover:
               group_id: 701
               ports: [25, 28]
     - rule:
         dl_type: 0x806
         dl_dst: "ff:ff:ff:ff:ff:ff"
         arp_tpa: "10.0.0.2"
         actions:
           output:
             failover:
               group_id: 801
               ports: [25, 28]
     - rule:
         dl_dst: "a0:36:9f:10:67:fe"
         actions:
           output:
             failover:
               group_id: 1202
               ports: [28, 25]
     - rule:
         dl_type: 0x86DD
         ip_proto: 58
         icmpv6_type: 135
         ipv6_nd_target: "2001:7f8:68::3"
         actions:
           output:
             failover:
               group_id: 1302
               ports: [28, 25]
     - rule:
         dl_type: 0x806
         dl_dst: "ff:ff:ff:ff:ff:ff"
         arp_tpa: "10.0.0.3"
         actions:
           output:
             failover:
               group_id: 1402
               ports: [28, 25]
     - rule:
         actions:
           allow: 0
   2:
     - rule:
         dl_dst: "a0:36:9f:10:67:fc"
         actions:
           output:
             failover:
               group_id: 1
               ports: [25, 28]
     - rule:
         dl_type: 0x86DD
         ip_proto: 58
         icmpv6_type: 135
         ipv6_nd_target: "2001:7f8:68::1"
         actions:
           output:
             failover:
               group_id: 100
               ports: [25, 28]
     - rule:
         dl_type: 0x806
         dl_dst: "ff:ff:ff:ff:ff:ff"
         arp_tpa: "10.0.0.1"
         actions:
           output:
             failover:
               group_id: 200
               ports: [25, 28]
     - rule:
         dl_dst: "a0:36:9f:10:67:fd"
         actions:
           output:
             port: 1
     - rule:
         dl_type: 0x86DD
         ip_proto: 58
         icmpv6_type: 135
         ipv6_nd_target: "2001:7f8:68::2"
         actions:
           output:
             port: 1
     - rule:
         dl_type: 0x806
         dl_dst: "ff:ff:ff:ff:ff:ff"
         arp_tpa: "10.0.0.2"
         actions:
           output:
             port: 1
     - rule:
         dl_dst: "a0:36:9f:10:67:fe"
         actions:
           output:
             failover:
               group_id: 1502
               ports: [26, 25]
     - rule:
         dl_type: 0x86DD
         ip_proto: 58
         icmpv6_type: 135
         ipv6_nd_target: "2001:7f8:68::3"
         actions:
           output:
             failover:
               group_id: 1602
               ports: [26, 25]
     - rule:
         dl_type: 0x806
         dl_dst: "ff:ff:ff:ff:ff:ff"
         arp_tpa: "10.0.0.3"
         actions:
           output:
             failover:
               group_id: 1702
               ports: [26, 25]
     - rule:
         actions:
           allow: 0
   3:
     - rule:
         dl_dst: "a0:36:9f:10:67:fc"
         actions:
           output:
             failover:
               group_id: 300
               ports: [28, 25]
     - rule:
         dl_type: 0x86DD
         ip_proto: 58
         icmpv6_type: 135
         ipv6_nd_target: "2001:7f8:68::1"
         actions:
           output:
             failover:
               group_id: 400
               ports: [28, 25]
     - rule:
         dl_type: 0x806
         dl_dst: "ff:ff:ff:ff:ff:ff"
         arp_tpa: "10.0.0.1"
         actions:
           output:
             failover:
               group_id: 500
               ports: [28, 25]
     - rule:
         dl_dst: "a0:36:9f:10:67:fd"
         actions:
           output:
             failover:
               group_id: 901
               ports: [25, 28]
     - rule:
         dl_type: 0x86DD
         ip_proto: 58
         icmpv6_type: 135
         ipv6_nd_target: "2001:7f8:68::2"
         actions:
           output:
             failover:
               group_id: 1001
               ports: [25, 28]
     - rule:
         dl_type: 0x806
         dl_dst: "ff:ff:ff:ff:ff:ff"
         arp_tpa: "10.0.0.2"
         actions:
           output:
             failover:
               group_id: 1101
               ports: [25, 28]
     - rule:
         dl_dst: "a0:36:9f:10:67:fe"
         actions:
           output:
             port: 1
     - rule:
         dl_type: 0x86DD
         ip_proto: 58
         icmpv6_type: 135
         ipv6_nd_target: "2001:7f8:68::3"
         actions:
           output:
             port: 1
     - rule:
         dl_type: 0x806
         dl_dst: "ff:ff:ff:ff:ff:ff"
         arp_tpa: "10.0.0.3"
         actions:
           output:
             port: 1
     - rule:
         actions:
           allow: 0
```
