### ISSUE TITLE
faucet reloads while the DP is disconnected are ineffective

### ISSUE THREAD

**Issue by gizmoguy** [faucetsdn/faucet#1801]
1. Start with a faucet instance with the following config and no connected DPs:

```
vlans:
    office:
        vid: 100
        description: "office network"

dps:
    sw1:
        dp_id: 0x1
        hardware: "Open vSwitch"
        interfaces:
            1:
                name: "p1"
                description: "port1"
                native_vlan: office
            2:
                name: "p2"
                description: "port2"
                native_vlan: office
```

2. Delete port 2 and reload faucet

3. Attach a DP with ID 0x1

4. Observe log file:

> Mar 21 03:00:12 faucet INFO     Loaded configuration from /etc/faucet/faucet.yaml
> Mar 21 03:00:12 faucet INFO     Add new datapath DPID 1 (0x1)
> Mar 21 03:00:22 faucet INFO     configuration /etc/faucet/faucet.yaml changed, analyzing differences
> Mar 21 03:00:23 faucet INFO     Reconfiguring existing datapath DPID 1 (0x1)
> Mar 21 03:00:23 faucet.valve INFO     DPID 1 (0x1) skipping configuration because datapath not up
> Mar 21 03:00:29 faucet INFO     DPID 1 (0x1) connected
> Mar 21 03:00:29 faucet.valve INFO     DPID 1 (0x1) Cold start configuring DP
> Mar 21 03:00:29 faucet.valve INFO     DPID 1 (0x1) Configuring VLAN office vid:100 ports:Port 1,Port 2
> Mar 21 03:00:29 faucet.valve INFO     DPID 1 (0x1) Port 1 configured
> Mar 21 03:00:29 faucet.valve INFO     DPID 1 (0x1) Port 2 configured
> Mar 21 03:00:29 faucet.valve INFO     DPID 1 (0x1) Ignoring port:4294967294 not present in configuration file

**Comment by gizmoguy** [comment]
Fixed in #1805

**Comment by Polpetta** [comment]
Hello,
following the [OVS Faucet Tutorial](http://docs.openvswitch.org/en/latest/tutorials/faucet/) me and @mzanella encountered the same issue, even using a version that includes the patch in #1805 (commit 41875c48414a2327f27c04eb56f5c511a76e1936).
Adding a bridge (from the OVS sandbox that can be made with `make sandbox`) with the following command:
```
ovs-vsctl add-br br0 \
         -- set bridge br0 other-config:datapath-id=0000000000000001 \
         -- add-port br0 p1 -- set interface p1 ofport_request=1 \
         -- add-port br0 p2 -- set interface p2 ofport_request=2 \
         -- add-port br0 p3 -- set interface p3 ofport_request=3 \
         -- add-port br0 p4 -- set interface p4 ofport_request=4 \
         -- add-port br0 p5 -- set interface p5 ofport_request=5 \
         -- set-controller br0 tcp:127.0.0.1:6653 \
         -- set controller br0 connection-mode=out-of-band
```
produces the following output in the `faucet.log` file:
```
Apr 24 09:12:29 faucet INFO     Loaded configuration from /etc/faucet/faucet.yaml
Apr 24 09:12:29 faucet INFO     Add new datapath DPID 1 (0x1)
Apr 24 09:12:50 faucet.valve INFO     DPID 1 (0x1) Cold start configuring DP
Apr 24 09:12:50 faucet.valve INFO     DPID 1 (0x1) Configuring VLAN 100 vid:100 ports:Port 1,Port 2,Port 3
Apr 24 09:12:50 faucet.valve INFO     DPID 1 (0x1) Configuring VLAN 200 vid:200 ports:Port 4,Port 5
Apr 24 09:12:50 faucet.valve INFO     DPID 1 (0x1) Port 1 configured
Apr 24 09:12:50 faucet.valve INFO     DPID 1 (0x1) Port 2 configured
Apr 24 09:12:50 faucet.valve INFO     DPID 1 (0x1) Port 3 configured
Apr 24 09:12:50 faucet.valve INFO     DPID 1 (0x1) Port 4 configured
Apr 24 09:12:50 faucet.valve INFO     DPID 1 (0x1) Port 5 configured
Apr 24 09:12:50 faucet.valve INFO     DPID 1 (0x1) Ignoring port:4294967294 not present in configuration file
```
We're using this `faucet.yaml` configuration file:
```yaml
dps:
    switch-1:
        dp_id: 0x1
        timeout: 3600
        arp_neighbor_timeout: 3600
        interfaces:
            1:
                native_vlan: 100
            2:
                native_vlan: 100
            3:
                native_vlan: 100
            4:
                native_vlan: 200
            5:
                native_vlan: 200
vlans:
    100:
    200:
```

Searching in the project code it seems that it comes out from https://github.com/faucetsdn/faucet/blob/master/faucet/valve.py#L591

We're trying to debug faucet but we're not obtaining any result at the moment.
Do you have any insight about that?
