### ISSUE TITLE
Configuration inconsistency between lldp org_tlvs and routes

### ISSUE THREAD

**Issue by KitL** [faucetsdn/faucet#1836]
When we have a list of configuration elements sometimes we list the configuration blocks directly and sometimes we keep them in a second dictionary.

This is needlessly unintuitive.

For example when we do things directly it looks like:
```
                    org_tlvs:
                        - {oui: 0x12bb, subtype: 2, info: "01406500"}
```

Or when we keep things in an additional dictionary it looks like this:
```
        routes:
            - route:
                ip_dst: 10.99.99.0/24
                ip_gw: 10.0.0.1
```

To me the org_tlvs approach seems more sensible. I propose we migrate to that approach (by first allowing both options).
