### ISSUE TITLE
Included configuration is ambiguous in certain circumstances

### ISSUE THREAD

**Issue by gizmoguy** [faucetsdn/faucet#2195]
In faucet we can include other files and create nested configuration. This is great for allowing us to reuse snippets and reduce overall configuration file size. It is bad when you put someone like me behind the wheel of the feature and I stuff things up.

So let's say we have a global VLAN configuration:

/etc/faucet/vlans.yml:
```
 ---
 vlans:
     bob:
         vid: 123
```

And then I include this in another file and accidentally reuse the vlan ID:

/etc/faucet/faucet.yml:
```
---
include:
    - vlans.yaml

 vlans:
     jane:
         vid: 123
         faucet_vips: ['192.168.0.1/24']

 dps:
     ovs:
         dp_id: 0x1
         hardware: "Open vSwitch"
         interfaces:
             1:
                 native_vlan: bob
             2:
                 tagged_vlans: [jane]
```

Now since I've re-used VLAN ID 123 twice, depending on which interface comes up first (1 or 2 on OVS) is whether VLAN ID 123 globally will have a VIP or not.

In future it would be nice to receive an error when the user adds conflicting configuration.
