### ISSUE TITLE
faucet can learn ban itself

### ISSUE THREAD

**Issue by gizmoguy** [faucetsdn/faucet#2227]
Take this config:
```
vlans:
    redcables-l3:
        name: "redcables-l3"
        description: "redcables ipv4/ipv6 vlan"
        vid: 250
        max_hosts: 255
        proactive_nd_limit: 4096
        faucet_mac: "0e:00:00:00:00:01"
        faucet_vips: [
            'fe80::c00:ff:fe00:1/64',                         # ipv6 link-local
            '163.7.137.254/24', '2404:138:4011:3e8::ffff/64', # gateway addresses
            ]
        targeted_gw_resolution: True
        routes:
            - route:
                ip_dst: '2404:138:4011::/64'
                ip_gw: '2404:138:4011:3e8::fffd'
            - route:
                ip_dst: '163.7.136.0/25'
                ip_gw: '163.7.137.252'
    my-l3:
        name: "my-l3"
        description: "my ipv4/ipv6 vlan"
        vid: 253
        max_hosts: 255
        proactive_nd_limit: 4096
        faucet_mac: "0e:00:00:00:02:53"
        faucet_vips: [
            'fe80::c00:00ff:fe00:0253/64',                    # ipv6 link-local
            '163.7.136.129/27', '2404:138:4011:9d04::1/64',   # gateway addresses
            ]
        targeted_gw_resolution: True
```

We see faucet may accidentally ban itself:

```
 cookie=0x5adc15c0, duration=156.084s, table=5, n_packets=28, n_bytes=2456, hard_timeout=371, priority=9227,ipv6,dl_vlan=250,ipv6_dst=fe80::c00:ff:fe00:1 actions=drop
 cookie=0x5adc15c0, duration=53.149s, table=5, n_packets=418, n_bytes=37620, hard_timeout=379, priority=9227,ipv6,dl_vlan=253,ipv6_dst=fe80::c00:ff:fe00:253 actions=drop
```
