### ISSUE TITLE
LACP bundles duplicate broadcast traffic down all member ports

### ISSUE THREAD

**Issue by gizmoguy** [faucetsdn/faucet#2386]
Take the following config:

```
            3:
                name: "Gi1/0/3"
                description: "ex4300-stack trunk-a"
                tagged_vlans: [redcables,redcables6]
                lacp: 8
            4:
                name: "Gi1/0/4"
                description: "ex4300-stack trunk-b"
                tagged_vlans: [redcables,redcables6]
                acl_in: protect_from_access
                lacp: 8
```

Broadcast packets on the attached VLANs seem to be duplicated across port 3 and 4:

```
15:16:35.859803 0e:00:00:00:00:01 > ff:ff:ff:ff:ff:ff, ethertype ARP (0x0806), length 60: Ethernet (len 6), IPv4 (len 4), Request who-has 163.7.137.97 tell 163.7.137.254, length 46
15:16:35.859843 0e:00:00:00:00:01 > ff:ff:ff:ff:ff:ff, ethertype ARP (0x0806), length 60: Ethernet (len 6), IPv4 (len 4), Request who-has 163.7.137.97 tell 163.7.137.254, length 46
```
