### ISSUE TITLE
Help configuring multi-DP routing

### ISSUE THREAD

**Issue by Dru90** [faucetsdn/faucet#2434]
Hello all,

I can't seem to get inter-vlan routing working at all. I have a Zodiac GX that is connected to a Zodiac FX - I believe I have trunked them together correctly (yaml config below). I can successfully ping the faucet_vip address of a vlan from a host attached to a port in the same native vlan (e.g. host with ip 172.16.0.50 connected to interface 1 on the Zodiac GX can ping 172.16.0.254). However I cannot ping from a host with ip 172.16.0.50 connected to interface 1 of the GX to a host with ip 10.0.0.50 connected to interface 2 of the FX.

I have set the Default GWs of both hosts to there respective faucet_vip. 

(Zodiac GX interface 4 is trunked to Zodiac FX interface 1)

I hope this makes sense, please help :)

```
version: 2

vlans:
        private:
                name: "private"
                vid: 100
                max_hosts: 255
                faucet_vips: ["172.16.0.254/16"]
        guest:
                name: "guest"
                vid: 200
                max_hosts: 255
                faucet_vips: ["10.0.0.254/24"]
routers:
        home-router:
                vlans: [private, guest]
dps:
        zodiacgx:
                dp_id: 0x************
                description: "ZodiacGX"
                hardware: "ZodiacGX"
                interfaces:
                        1:
                                name: "eth0.1"
                                native_vlan: private
                        2:
                                name: "eth0.2"
                                native_vlan: private
                        3:
                                name: "eth0.3"
                                native_vlan: private
                        4:
                                name: "eth0.4"
                                tagged_vlans: [private,guest]
        zodiacfx:
                dp_id: 0x************
                description: "ZodiacFX"
                hardware: "ZodiacFX"
                interfaces:
                        1:
                                tagged_vlans: [private,guest]
                        2:
                                native_vlan: guest
                        3:
                                native_vlan: guest
```

**Comment by Dru90** [comment]
@gizmoguy ok I'll do that. How would I go about doing that? Can I keep both datapaths in the .yaml file? If so must I create a separate vlan to be used natively with the FX only?

**Comment by Dru90** [comment]
@gizmoguy ! sorry one more question - how would I connect a router to the Zodiac GX as the route to the internet? I can ping my router from a host connected to the GX but cannot achieve an internet connection. I suspect I may need to configure a static route in Faucet config file?

**Comment by gizmoguy** [comment]
A common pattern in faucet is to have the concept of an L2 controller and and L3 controller. Both of which use the same VLAN IDs but have different VLAN configuration (one with routing enabled and another without).

I have some examples here of how this works on my faucet network:

https://github.com/wandsdn/redcables-ansible/tree/testing/files/faucet

In terms of your question around joining the internet to your faucet network with a separate router. Is there any chance you could draw up a quick diagram of what you want to achieve with some subnetting and VLAN information and I'll help you write some faucet config to make the topology work.

**Comment by Dru90** [comment]
![20180908_010909](https://user-images.githubusercontent.com/42614550/45248027-47c2f400-b304-11e8-9e72-81abebd5db65.jpg)

Hows that? Heres my edited config below. I've tried it using IVR just on the GX but no luck.

version: 2

vlans:
        private:
                name: "private"
                vid: 100
                max_hosts: 255
                faucet_vips: ["172.16.0.254/16"]
        guest:
                name: "guest"
                vid: 200
                max_hosts: 255
                faucet_vips: ["10.0.0.254/24"]
routers:
        home-router:
                vlans: [private, guest]
dps:
        zodiacgx:
                dp_id: 0x************
                description: "ZodiacGX"
                hardware: "ZodiacGX"
                interfaces:
                        1:
                                name: "eth0.1"
                                native_vlan: private
                        2:
                                name: "eth0.2"
                                native_vlan: private
                        3:
                                name: "eth0.3"
                                native_vlan: guest
                        4:
                                name: "eth0.4"
                                native_vlan: private
        zodiacfx:
                dp_id: 0x************
                description: "ZodiacFX"
                hardware: "ZodiacFX"
                interfaces:
                        1:
                                native_vlan: private
                        2:
                                native_vlan: private
                        3:
                                native_vlan: private

Interface 4 on the GX connects to Interface 1 on the FX.
Interface 1 on the GX connects to LAN port 2 on the Router (router is flashed with openwrt).

**Comment by gizmoguy** [comment]
Hi @Dru90 

You will need to run two faucet controllers, here is the config for the first one:

/etc/faucet/faucet-l3.yaml
```
vlans:
  private-l3:
    name: "private"
    vid: 100
    max_hosts: 255
    faucet_vips: ["172.16.0.254/16"]
  guest-l3:
    name: "guest"
    vid: 200
    max_hosts: 255
    faucet_vips: ["10.0.0.254/24"]
routers:
  home-router:
    vlans: [private-l3, guest-l3]
dps:
  zodiacgx:
    dp_id: 0x************
    description: "ZodiacGX"
    hardware: "ZodiacGX"
    interfaces:
      1:
        name: "eth0.1"
        native_vlan: private-l3
      2:
        name: "eth0.2"
        native_vlan: private-l3
      3:
        name: "eth0.3"
        native_vlan: guest-l3
      4:
        name: "eth0.4"
        native_vlan: private-l3
```

and here is the config for the second:

faucet-l2.yaml
```
vlans:
  private:
    name: "private"
    vid: 100
    max_hosts: 255
  guest:
    name: "guest"
    vid: 200
    max_hosts: 255
dps:
  zodiacfx:
      dp_id: 0x************
      description: "ZodiacFX"
      hardware: "ZodiacFX"
      interfaces:
        1:
          native_vlan: private
        2:
          native_vlan: private
        3:
          native_vlan: private
```

If using the apt package it is pretty easy to spin up additional controllers, something like this should work:

$ cp /etc/default/faucet /etc/default/faucet-l2
$ cp /etc/default/faucet /etc/default/faucet-l3
$ cp /lib/systemd/system/faucet.service /etc/systemd/system/faucet-l2.service
$ cp /lib/systemd/system/faucet.service /etc/systemd/system/faucet-l3.service

Then we need to edit /etc/default/faucet-l2 and /etc/default/faucet-l3 changing the FAUCET_LISTEN_PORT and FAUCET_PROMETHEUS_PORT so they are both listening on different ports. Also edit FAUCET_CONFIG, FAUCET_LOG, FAUCET_EXCEPTION_LOG so that each controller loads the right configuration file and logs to a sensible place.

We then edit /etc/systemd/system/faucet-l2.service and /etc/systemd/system/faucet-l3.service changing which EnvironmentFile is loaded.

Now we can do some systemd magic to enable the new controllers and disable the old one:

$ systemctl daemon-reload
$ systemctl disable faucet
$ systemctl enable faucet-l2
$ systemctl enable faucet-l3
$ systemctl start faucet-l2
$ systemctl start faucet-l3

Finally point your datapaths to the new openflow ports we assigned using the FAUCET_LISTEN_PORT environment variable we changed above.

**Comment by Dru90** [comment]
Ok I've done all that with the exception of adding a static route to the router, because I've disconnected the router for the moment. I would like to get IVR working first:

- I still am unable to route between vlans on the GX. One laptop is connected to interface 2 of the GX with ip-address 172.16.0.45 255.255.0.0 gw 172.16.0.254 and when I ping the laptop connected to interface 3 on the GX with ip-address 10.0.0.50 255.255.255.0 gw 10.0.0.254 I receive the message request timed out.

- Also the Zodiac FX has disappeared from the inventory dashboard in Grafana - can I get this back?

**Comment by Dru90** [comment]
the gauge log output:

pi@raspberrypi:/etc/faucet $ tail /var/log/faucet/gauge.log 
    return _watcher_parser_v2(conf, logname, prom_client)
  File "/usr/lib/python3/dist-packages/faucet/config_parser.py", line 266, in _watcher_parser_v2
    dps = _parse_dps_for_watchers(conf, logname)
  File "/usr/lib/python3/dist-packages/faucet/config_parser.py", line 240, in _parse_dps_for_watchers
    _, dp_list = dp_parser(faucet_file, logname)
  File "/usr/lib/python3/dist-packages/faucet/config_parser.py", line 43, in dp_parser
    conf = config_parser_util.read_config(config_file, logname)
  File "/usr/lib/python3/dist-packages/faucet/config_parser_util.py", line 69, in read_config
    with open(config_file, 'r') as stream:
TypeError: invalid file: ['/etc/faucet/faucet-l3.yaml']

**Comment by Dru90** [comment]
@shivarammysore yeah i worked that out so deleted from the earlier post. cheers

**Comment by Dru90** [comment]
Brilliant that is good news! I'll do this

_To answer the question on the whiteboard diagram of "how do I make this a trunk link?", all you need to do to is change native_vlan: private to tagged_vlans: [private] (and private-l3 on the l3 controller). This is a list of vlans and you can add as many as you want._  -- Say if I change a port on the FX to [native: guest] would either end of the trunk link then need to be [tagged_vlans: private, guest] - for FX and [tagged_vlans: private-l3, guest-l3] - for GX to allow both networks across the trunk.

Log and yaml files attached - yaml files have a meter and acl included by they arent applied to any interfaces at the moment:

[faucet-l2.log](https://github.com/faucetsdn/faucet/files/2364188/faucet-l2.log)
[faucet-l3.log](https://github.com/faucetsdn/faucet/files/2364189/faucet-l3.log)
[faucet-l2.yaml.txt](https://github.com/faucetsdn/faucet/files/2364190/faucet-l2.yaml.txt)
[faucet-l3.yaml.txt](https://github.com/faucetsdn/faucet/files/2364191/faucet-l3.yaml.txt)

**Comment by Dru90** [comment]
@gizmoguy Hi Brad, you can probably ignore my previous post if you haven't read it yet, everything below will be more up to date with my progress.

Most recent diagram:
![20180909_194731](https://user-images.githubusercontent.com/42614550/45267718-e9b02100-b469-11e8-95a8-73cedb908dc9.jpg)

I've managed to bridge a software vlans with CPU ETH0 on the openwrt router to create 2 virtual interfaces. I create vlan 100 (private) and 200 (guest) and bridged each of them with ETH0 CPU to create 2 separate interfaces that both provide a dhcp service. This along with the static route you suggested allowed me to successfully trunk both vlans to the router and get a dhcp ip address and internet connnection for the hosts connected directly to the GX (as shown in diagram). 

However I'm unable to connect to the router from hosts connected to the FX. I think it may be an issue with the trunk between the GX and FX although I'm sure its configured correctly. I know I said in the previous post that I got the trunk link to work but that was before I added the trunk from the GX back to the router. I think im missing something. 

Provided router configuration screenshots below as well as updated yaml files and logs:
![2018-09-09-192825_1824x984_scrot](https://user-images.githubusercontent.com/42614550/45267772-4a8c2900-b46b-11e8-9048-e0b741a7416e.png)
![2018-09-09-192918_1824x984_scrot](https://user-images.githubusercontent.com/42614550/45267773-4a8c2900-b46b-11e8-8d7b-1187baa09e6b.png)
![2018-09-09-192932_1824x984_scrot](https://user-images.githubusercontent.com/42614550/45267774-4a8c2900-b46b-11e8-88cd-8b75a3096b7c.png)
![2018-09-09-192942_1824x984_scrot](https://user-images.githubusercontent.com/42614550/45267775-4a8c2900-b46b-11e8-9d25-c6a313c20fde.png)
[faucet-l2.log](https://github.com/faucetsdn/faucet/files/2364556/faucet-l2.log)
[faucet-l2.yaml.txt](https://github.com/faucetsdn/faucet/files/2364557/faucet-l2.yaml.txt)
[faucet-l3.log](https://github.com/faucetsdn/faucet/files/2364558/faucet-l3.log)
[faucet-l3.yaml.txt](https://github.com/faucetsdn/faucet/files/2364559/faucet-l3.yaml.txt)


So what is working:
hosts in either private or guest vlan connected to the GX directly pull a dhcp ip address from the router and can connect to the internet. 

What isn't working:
- IVR on the GX
- hosts in either private or guest vlan connected to the FX are unable to pull a dhcp ip address and even when the are assigned a static the cannot ping anything else on the network.

side note:
- i updated the firmware on the GX successfully

Really appreciate your help so far

Dru

**Comment by anarkiwi** [comment]
If IVR using the same config as the tests does not work, this suggests an issue with the switch. FAUCET provides integration tests against OVS and hardware. It may be a good use of time for you to verify that the IVR test passes on your switch. If it doesn't, then you can pursue the question with the switch vendor. If it does pass, then that suggests something else in the config or environment.

**Comment by Dru90** [comment]
- interestingly after checking the routers logs I can see that the router does discover hosts connected to the FX and responds with an offer but I dont think the offer ever gets back to the host. Log below:

Sun Sep  9 22:36:31 2018 daemon.info dnsmasq-dhcp[26126]: DHCPDISCOVER(br-lan) d8:cb:8a:83:75:74 
Sun Sep  9 22:36:31 2018 daemon.info dnsmasq-dhcp[26126]: DHCPOFFER(br-lan) 172.16.0.117 d8:cb:8a:83:75:74 
Sun Sep  9 22:36:32 2018 daemon.info dnsmasq-dhcp[26126]: DHCPDISCOVER(br-lan) d8:cb:8a:83:75:74 
Sun Sep  9 22:36:32 2018 daemon.info dnsmasq-dhcp[26126]: DHCPOFFER(br-lan) 172.16.0.117 d8:cb:8a:83:75:74 
Sun Sep  9 22:36:37 2018 daemon.info dnsmasq-dhcp[26126]: DHCPDISCOVER(br-lan) d8:cb:8a:83:75:74 
Sun Sep  9 22:36:37 2018 daemon.info dnsmasq-dhcp[26126]: DHCPOFFER(br-lan) 172.16.0.117 d8:cb:8a:83:75:74

**Comment by Dru90** [comment]
@gizmoguy By two routers do you mean the 172.16.0.1 of the router and the 172.16.0.254 of the switch?

and can you explain why I would add a third vlan, sorry I'm slightly confused!

Dru

**Comment by Dru90** [comment]
@gizmoguy I guess im setting up for concept purposes only so I could change it up what would you recommend in terms of topology?

**Comment by gizmoguy** [comment]
Yes by the two routers I mean 172.16.0.1 and 172.16.0.254. You aren't meant to route on a single L2 domain and you have to remember that Inter-VLAN Routing (IVR) in faucet is real L3 routing.

Something more like this work work better:

![dru90 proposed network architecture](https://user-images.githubusercontent.com/383287/45270544-b1085a00-b4f2-11e8-8ace-affb2cf5ca9a.png)

**Comment by Dru90** [comment]
Ok thanks for the diagram I'll give this a try. In this design would all hosts be-able to access internet?

From what I understand:
- zodiac gx port connected to host1 --> native vlan: 20
- zodiac gx port connected to host2 --> native: 30
- zodiac gx port connected to zodiac fx --> tagged vlans: [20,30]
- zodiac gx port connected to router --> native vlan: 10
- zodiac fx port connected to host3 --> native vlan: 20
- zodiac fx port connected to zodiac gx --> tagged vlans: [20,30]

- apply all 3 faucet vlan vips to the zodiac gx
- apply all 3 vlans to the zodiac fx

Would I need any other config?

Dru

**Comment by gizmoguy** [comment]
In my design everything will be able to access the internet yes (as long as you add all 3 vlans to the "router" section of the config).

Your understanding looks correct, you will also need to add a static route to the internet vlan, you can see an example of how to do that in this sample configuration:

https://faucet.readthedocs.io/en/latest/configuration.html?highlight=route#faucet-yaml

**Comment by Dru90** [comment]
that would look like 0.0.0.0/0 via internet gw ?

**Comment by Dru90** [comment]
@gizmoguy I've gone through and done that carefully. I even included a faucet_mac for each vlan on the GX. 

The GX won't perform IVR no matter what I try. I can ping the faucet_vip associated with the native_vlan the host is on (e.g. 10.0.20.1 can ping 10.0.20.254). But when I attempt to ping 10.0.30.254 or a host 10.0.30.1 from 10.0.20.1 I get nothing.....

Have you tried this with the GX? I wonder if its a problem with the HW

**Comment by gizmoguy** [comment]
The GX does pass our integration tests for IVR:

```
test_untagged (mininet_tests.FaucetUntaggedIPv4InterVLANRouteTest) ... ok
test_untagged (mininet_tests.FaucetUntaggedIPv6InterVLANRouteTest) ... ok
```

If you can attach your faucet-l2.yaml and faucet-l3.yaml I will try and replicate your setup here and see if I can get to the bottom of it when I have some free time tomorrow.

**Comment by Dru90** [comment]
Thanks I hope its do-able! 

My routers gateway is now: 192.168.1.1

[faucet-l2.yaml.txt](https://github.com/faucetsdn/faucet/files/2364924/faucet-l2.yaml.txt)
[faucet-l3.yaml.txt](https://github.com/faucetsdn/faucet/files/2364925/faucet-l3.yaml.txt)

**Comment by Dru90** [comment]
@gizmoguy Hi, I have an update! IVR is now working on my GX. It was windows firewall (all my hosts are windows pcs) blocking remote subnets! After adding a rule to allow the remote subnets IVR worked as expected. 

still not working:
- My trunk link is still not letting any traffic through between the GX and FX - both ends are tagged as can be seen in yaml files.
- No hosts can connect to the internet. Im setting the default gateway of each host as a faucet_vip as can be seen in the yaml files.

ive changed my router to a ddwrt acm3200 with ip 192.168.1.1. 

Applied 2 static routes to the router: 
- 192.168.2.0/24 via 192.168.1.96 (private vlan vip) 
- 192.168.3.0/24 via 192.168.1.96 (private vlan vip)
- do I need any more?

**Comment by gizmoguy** [comment]
Hi @Dru90,

Great to hear you got IVR working. What IP were you using for DNS prior to using 192.168.1.1?

Regarding the trunk link to the FX, I would initially suspect the FX is to blame here, it is a pretty barebones device and we haven't tested it against recent version of faucets so I'm not sure it works. Would you be able to plug a regular PC into the trunk port (instead of the FX) and try tagging one of your VLANs and see if it connects? That will help us rule out the FX dropping traffic.

**Comment by Dru90** [comment]
I was pulling the ipaddress from dhcp so I suspect it may have been 192.168.1.1 before. Do you think it would be possible to have the 192.168.2.0 and 192.168.3.0 subnets pull an ipaddress from dhcp from the router?

Ok give me a second I'll try that with the trunk port now

**Comment by gizmoguy** [comment]
DHCP requires Layer 2 connectivity for discovery so your router will not be able to supply this information (it is connected via L3 now). A common design pattern for faucet is to have an NFV host connected to your GX that is tagged on all VLANs and faucet can divert traffic such as DHCP to this host so it can answer queries.

**Comment by Dru90** [comment]
Or do you mean only tag 1 vlan on the trunk (guest vlan) then connect a pc (192.168.2.30) and try to ping a pc (192.168.2.60) on port with native vlan 200?

**Comment by Dru90** [comment]
^^ I tried both those methods on the GX and couldnt get a connection....

**Comment by Dru90** [comment]
@gizmoguy I posted a couple of times earlier but deleted them because they're not relevant now - so if you got an email for a post you don't see here just ignore it.

So I set my pc NIC to vlan 200 (guest) and connect it to the Zodiac GX trunk (config: tagged vlans: [guest-l3, test-l3]. Then I connected a second pc (untagged) to a port on the Zodiac GX (config: native vlan: guest) and sent a ping to the first pc, it succeeded!! I tried to recreate this exact same setup using the Zodiac FX and it didn't work at all. So yes I believe you are correct the Zodiac FX is dropping traffic whenever it passes through a trunk (tagged vlans) port. Do you think they'll be a fix for this or is a limitation of the Zodiac FX with Faucet?

What you might be interested to know is IVR is working between the Zodiac GX and Zodiac FX when I connect them together untagged/untrunked (when both ends of connection share same native vlan). So I'm able to IVR from the guest network on the FX to the private network on the GX no problem at all.

**Comment by gizmoguy** [comment]
Glad to hear the GX now works as expected.

Regarding the Zodiac FX problems, could you let me know what firmware version you are running? I will spin up one of mine here and see if I can track down the problem the tagged VLAN problem. Zodiac FX is an open source project so best we can do is submit a bug report on their repo and see if they are able to fix.

**Comment by Dru90** [comment]
Firmware version 0.84, I think its the most recent

Sounds good, let me know how it goes. Thanks for your help with these issues! I plan to implement a SDN home network for my final year uni project so this has all been really useful.

**Comment by gizmoguy** [comment]
Okay I narrowed down why the zodiacfx doesn't work under 0.84.

I have a faucet configured as such (redcables has a VID of 250):

```
    zodiacfx:
        dp_id: 0x70b3d56cd023
        description: "zodiacFX"
        hardware: "ZodiacFX"
        interfaces:
            1:
                name: "eth0.1"
                native_vlan: redcables
            2:
                name: "eth0.2"
                native_vlan: redcables
            3:
                name: "eth0.3"
                tagged_vlans: [redcables]
```

We see the following flow installed on the ZodiacFX to handle traffic coming in on port 3, VLAN 250 and it will pass the along the pipeline:

```
Flow 14
 Match:
  In Port: 3
  VLAN ID: 250
 Attributes:
  Table ID: 0                           Cookie:0x5adc15c0
  Priority: 9000                                Duration: 154 secs
  Hard Timeout: 0 secs                  Idle Timeout: 0 secs
  Byte Count: 0                 Packet Count: 0
  Last Match: 00:02:34
 Instructions:
  Goto Table: 1
```

The ZodiacFX tells me no bytes are matching this flow despite my networking sending traffic on this vlan ID to this port. Interestingly enough I do see traffic go from the untagged ports to the tagged port, just no traffic in the other direction.

Could you confirm you see the same on yours then you will want to submit a bug upstream here:

https://github.com/northboundnetworks/zodiacfx/issues
