### ISSUE TITLE
Move BGP* config to Router

### ISSUE THREAD

**Issue by anarkiwi** [faucetsdn/faucet#2563]
Where it will be a lot more useful for global router type scenarios.

**Comment by gizmoguy** [comment]
Because faucet BGP can only be enabled in a single VLAN, when multihoming we would want to do something like:

```
    bgp-nfv:
        description: 'linux bird peering'
        vid: 4092
        max_hosts: 10
        faucet_mac: '0e:00:00:00:40:92'
        bgp_routerid: '127.0.0.2'
        bgp_as: 65000
        bgp_neighbor_as: 65000
        bgp_neighbor_addresses: ['127.0.0.1', '::1']
        bgp_server_addresses: ['127.0.0.2', '::1']
        bgp_port: 9179
        bgp_connect_mode: 'passive'
    rtr1:
        description: 'rtr1 peering'
        vid: 2010
        max_hosts: 10
        faucet_mac: '0e:00:00:00:20:10'
        faucet_vips:
          - '1.1.1.3/29'
          - '2001::3/112'
    rtr2:
        description: 'rtr2 peering'
        vid: 2020
        max_hosts: 10
        faucet_mac: '0e:00:00:00:20:20'
        faucet_vips:
          - '2.2.2.3/29'
          - '2002::3/112'
```

This won't work currently as faucet does not let you resolve next hops in other VLANs:

> faucet.valve INFO     DPID 119762378579559 (0x6cec5a085e67) faucet-rtr Not resolving    2.2.2.1 (not in connected network)
