### ISSUE TITLE
Gauge: dps and all_dps should not be able to be set at same time

### ISSUE THREAD

**Issue by gizmoguy** [faucetsdn/faucet#2618]
This is invalid config, but currently gauge allows it:

```
 watchers:
     port_stats_poller:
         type: 'port_stats'
         dps: []
         all_dps: True
         interval: 10
         db: 'prometheus'
```
