### ISSUE TITLE
intervlan routing with multiple dp connected with trunks does not work 

### ISSUE THREAD

**Issue by kstest1** [faucetsdn/faucet#2672]
I have 3 dp: s1, s2, s3.  Configured vlans: 100 and 200. Configured router on vl100 and vl200. 
**Switch connections:**
s1, port 20 (of port1 -see config)  connects to s2, port 20  (of port1) . vlan 100 and 200 allowed with tagging.
s2, port 21 (of port2)  connects to s3, port 21. (of port2) vlan 100 and 200 allowed with tagging.
**Host connections:**
On s1, port 22  (of port3) , there is host h1 in native vlan 100 ( ip 10.0.100.51/24, d.g. 10.0.100.254) 
On s3, port 22  (of port3) , there is host h2 in native vlan 200.( ip 10.0.200.52/24, d.g. 10.0.200.254) 
On s3, port 20  (of port1) , there is host h3 in native vlan 100.( ip 10.0.100.53/24, d.g. 10.0.100.254) 
**Result:**
h1 can ping h3 in same vlan. 
h2 can ping h3 in different vlan ( they are on s3 switch).
h1 can NOT ping h2 in different vlan ( they are on s1 /s3  switches connected via s2).

**Reason:** 
When h2 pings h1, s3 needs to know arp info for h1 in vlan 100. arp is generated from faucet and sent from s3 , port 21  to s2, port21. This packet is dropped on s2 as came from faucet vip dl address. Even if it is allowed by config, return packet ARP will be taken by  s1 as reply go to same mac address and s3 will not know mapping. 

**Config** 
(   test with  hardware: "GenericTFM", same with other hw) 
```

test#more /etc/faucet/faucet.yaml 
include:
   - acls.yaml


vlans:
    office:
        vid: 100
        description: "office network"
        faucet_mac: "0e:00:00:00:10:01"
        faucet_vips: ['10.0.100.254/24', '2001:100::1/64', 'fe80::c00:00ff:fe00:1001/64']
    guest:
        vid: 200
        description: "guest network"
        faucet_mac: "0e:00:00:00:20:01"
        faucet_vips: ['10.0.200.254/24', '2001:200::1/64', 'fe80::c00:00ff:fe00:2001/64']

routers:
    router-office-guest:
        vlans: [office, guest]

dps:
    sw1:
        dp_id: 0x1
        hardware: "GenericTFM"
        interfaces:
            3:
                name: "if22"
                description: "if22-offvl"
                native_vlan: office
            1:
                name: "if20"
                description: "trunk to sw2"
                tagged_vlans: [office, guest]

    sw2:
        dp_id: 0x2
        hardware: "GenericTFM"
        interfaces:
            1:
                name: "if20"
                description: "trunk to sw1"
                tagged_vlans: [office, guest]

            2:
                name: "if21"
                description: "trunk to sw3"
                tagged_vlans: [office, guest]

    sw3:
        dp_id: 0x3
        hardware: "GenericTFM"
        interfaces:

            2:
                name: "if21"
                description: "trunk to sw2"
                tagged_vlans: [office, guest]


            3:
                name: "if22"
                description: "if22-guestvl"
                native_vlan: guest

            1:
                name: "if20"
                description: "if22-offvl"
                native_vlan: office

```
**Tables 0 and 1 flows on s2**

 OFPST_FLOW reply (OF1.3) (xid=0x2):
 cookie=0x5adc15c0, duration=18.748s, table=0, n_packets=0, n_bytes=0, priority=9000,in_port=1,dl_vlan=100 actions=goto_table:1
 cookie=0x5adc15c0, duration=18.748s, table=0, n_packets=0, n_bytes=0, priority=9000,in_port=1,dl_vlan=200 actions=goto_table:1
 **cookie=0x5adc15c0, duration=18.747s, table=0, n_packets=2, n_bytes=120, priority=9000,in_port=2,dl_vlan=100 actions=goto_table:1**
 cookie=0x5adc15c0, duration=18.747s, table=0, n_packets=0, n_bytes=0, priority=9000,in_port=2,dl_vlan=200 actions=goto_table:1
 cookie=0x5adc15c0, duration=18.747s, table=0, n_packets=0, n_bytes=0, priority=0 actions=drop
 cookie=0x5adc15c0, duration=18.751s, table=1, n_packets=0, n_bytes=0, priority=9100,dl_src=ff:ff:ff:ff:ff:ff actions=drop
 cookie=0x5adc15c0, duration=18.751s, table=1, n_packets=0, n_bytes=0, priority=9100,dl_src=0e:00:00:00:20:01 actions=drop
 **cookie=0x5adc15c0, duration=18.750s, table=1, n_packets=2, n_bytes=120, priority=9100,dl_src=0e:00:00:00:10:01 actions=drop**
 cookie=0x5adc15c0, duration=18.751s, table=1, n_packets=0, n_bytes=0, priority=9100,dl_type=0x9000 actions=drop
 cookie=0x5adc15c0, duration=18.750s, table=1, n_packets=0, n_bytes=0, priority=9099,arp,dl_vlan=200 actions=goto_table:4
 cookie=0x5adc15c0, duration=18.750s, table=1, n_packets=0, n_bytes=0, priority=9099,arp,dl_vlan=100 actions=goto_table:4
 cookie=0x5adc15c0, duration=18.750s, table=1, n_packets=0, n_bytes=0, priority=9099,ip,dl_vlan=200,dl_dst=0e:00:00:00:20:01 actions=goto_table:2
 cookie=0x5adc15c0, duration=18.750s, table=1, n_packets=0, n_bytes=0, priority=9099,ipv6,dl_vlan=200,dl_dst=33:33:ff:00:00:01 actions=goto_table:4
 cookie=0x5adc15c0, duration=18.750s, table=1, n_packets=0, n_bytes=0, priority=9099,ipv6,dl_vlan=200,dl_dst=0e:00:00:00:20:01 actions=goto_table:3
 cookie=0x5adc15c0, duration=18.750s, table=1, n_packets=0, n_bytes=0, priority=9099,ipv6,dl_vlan=200,dl_dst=33:33:00:00:00:02 actions=goto_table:4
 cookie=0x5adc15c0, duration=18.750s, table=1, n_packets=0, n_bytes=0, priority=9099,ipv6,dl_vlan=200,dl_dst=33:33:ff:00:20:01 actions=goto_table:4
 cookie=0x5adc15c0, duration=18.750s, table=1, n_packets=0, n_bytes=0, priority=9099,ip,dl_vlan=100,dl_dst=0e:00:00:00:10:01 actions=goto_table:2
 cookie=0x5adc15c0, duration=18.750s, table=1, n_packets=0, n_bytes=0, priority=9099,ipv6,dl_vlan=100,dl_dst=33:33:ff:00:00:01 actions=goto_table:4
 cookie=0x5adc15c0, duration=18.750s, table=1, n_packets=0, n_bytes=0, priority=9099,ipv6,dl_vlan=100,dl_dst=0e:00:00:00:10:01 actions=goto_table:3
 cookie=0x5adc15c0, duration=18.750s, table=1, n_packets=0, n_bytes=0, priority=9099,ipv6,dl_vlan=100,dl_dst=33:33:00:00:00:02 actions=goto_table:4
 cookie=0x5adc15c0, duration=18.750s, table=1, n_packets=0, n_bytes=0, priority=9099,ipv6,dl_vlan=100,dl_dst=33:33:ff:00:10:01 actions=goto_table:4
 cookie=0x5adc15c0, duration=18.749s, table=1, n_packets=0, n_bytes=0, priority=9000,dl_vlan=200 actions=CONTROLLER:96,goto_table:5
 cookie=0x5adc15c0, duration=18.748s, table=1, n_packets=0, n_bytes=0, priority=9000,dl_vlan=100 actions=CONTROLLER:96,goto_table:5
 cookie=0x5adc15c0, duration=18.747s, table=1, n_packets=0, n_bytes=0, priority=0 actions=goto_table:5
