### ISSUE TITLE
Faucet doesn't configure newly added ports on reload

### ISSUE THREAD

**Issue by gizmoguy** [faucetsdn/faucet#2728]
Create a switch with 4 ports.

Start faucet with the following configuration:

```
vlans:
    office:
        vid: 100
        description: "office network"

dps:
    sw1:
        dp_id: 0x1
        hardware: "Open vSwitch"
        interfaces:
            1:
                name: "host1"
                description: "host2 network namespace"
                native_vlan: office
            2:
                name: "host2"
                description: "host2 network namespace"
                native_vlan: office
```

Then we add some new ports:

```
vlans:
    office:
        vid: 100
        description: "office network"

dps:
    sw1:
        dp_id: 0x1
        hardware: "Open vSwitch"
        interfaces:
            1:
                name: "host1"
                description: "host1 network namespace"
                native_vlan: office
            2:
                name: "host2"
                description: "host2 network namespace"
                native_vlan: office
            3:
                name: "host3"
                native_vlan: office
            4:
                name: "host4"
                native_vlan: office
```

If we reload faucet we will see it almost gets it right:

> Jan 17 10:35:33 faucet INFO     Reloading configuration
> Jan 17 10:35:33 faucet INFO     configuration /etc/faucet/faucet.yaml changed, analyzing differences
> Jan 17 10:35:33 faucet INFO     Reconfiguring existing datapath DPID 1 (0x1)
> Jan 17 10:35:33 faucet.valve INFO     DPID 1 (0x1) sw1 VLAN 100 config changed
> Jan 17 10:35:33 faucet.valve INFO     DPID 1 (0x1) sw1 port 3 added
> Jan 17 10:35:33 faucet.valve INFO     DPID 1 (0x1) sw1 port 4 added
> Jan 17 10:35:33 faucet.valve INFO     DPID 1 (0x1) sw1 all ports changed
> Jan 17 10:35:33 faucet.valve INFO     DPID 1 (0x1) sw1 table ID 0 table config match_types: (('eth_dst', True), ('eth_type', False), ('in_port', False), ('vlan_vid', False)) name: vlan next_tables: ['eth_src'] output: True set_fields: ('vlan_vid',) size: 32 vlan_port_scale: 1.5
> Jan 17 10:35:33 faucet.valve INFO     DPID 1 (0x1) sw1 table ID 1 table config match_types: (('eth_dst', True), ('eth_src', False), ('eth_type', False), ('in_port', False), ('vlan_vid', False)) miss_goto: eth_dst name: eth_src next_tables: ['eth_dst', 'flood'] output: True set_fields: ('vlan_vid', 'eth_dst') size: 32 table_id: 1 vlan_port_scale: 4.1
> Jan 17 10:35:33 faucet.valve INFO     DPID 1 (0x1) sw1 table ID 2 table config exact_match: True match_types: (('eth_dst', False), ('vlan_vid', False)) miss_goto: flood name: eth_dst output: True size: 32 table_id: 2 vlan_port_scale: 4.1
> Jan 17 10:35:33 faucet.valve INFO     DPID 1 (0x1) sw1 table ID 3 table config match_types: (('eth_dst', True), ('in_port', False), ('vlan_vid', False)) name: flood output: True size: 32 table_id: 3 vlan_port_scale: 2.1
> Jan 17 10:35:33 faucet.valve INFO     DPID 1 (0x1) sw1 Cold start configuring DP
> Jan 17 10:35:33 faucet.valve INFO     DPID 1 (0x1) sw1 Port 1 (host1 network namespace) configured
> Jan 17 10:35:33 faucet.valve INFO     DPID 1 (0x1) sw1 Port 2 (host2 network namespace) configured
> Jan 17 10:35:33 faucet.valve INFO     DPID 1 (0x1) sw1 Configuring VLAN office vid:100 untagged: Port 1,Port 2,Port 3,Port 4
> Jan 17 10:35:33 faucet.valve INFO     DPID 1 (0x1) sw1 cold starting

However the rules for the new ports will not be added to the VLAN table (possibly faucet doesn't do the port aliveness check on reloads?):

> brad@faucet-tutorial:~$ sudo ovs-ofctl -OOpenFlow13 dump-flows br0 | grep table=0
>  cookie=0x5adc15c0, duration=120.064s, table=0, n_packets=0, n_bytes=0, priority=9000,in_port=1,vlan_tci=0x0000/0x1fff actions=push_vlan:0x8100,set_field:4196->vlan_vid,goto_table:1
>  cookie=0x5adc15c0, duration=120.064s, table=0, n_packets=1, n_bytes=70, priority=9000,in_port=2,vlan_tci=0x0000/0x1fff actions=push_vlan:0x8100,set_field:4196->vlan_vid,goto_table:1
>  cookie=0x5adc15c0, duration=120.064s, table=0, n_packets=2, n_bytes=140, priority=0 actions=drop
