### ISSUE TITLE
Faucet IVR breaks when hosts move port and faucet is sent SIGHUP

### ISSUE THREAD

**Issue by gizmoguy** [faucetsdn/faucet#2759]
Let's say we have host1 (10.0.0.1/24) and host2 (10.0.1.1/24).

Let's boot a clean faucet with the following configuration:

```
vlans:
    vlan100:
        vid: 100
        faucet_vips: ["10.0.0.254/24"]
        faucet_mac: "00:00:00:00:00:11"
    vlan200:
        vid: 200
        faucet_vips: ["10.0.1.254/24"]
        faucet_mac: "00:00:00:00:00:22"
routers:
    router-1: 
        vlans: [vlan100, vlan200]
dps:
    sw1:
        dp_id: 0x1
        hardware: "Open vSwitch"
        interfaces:
            1:
                name: "host1"
                description: "host1 network namespace"
                native_vlan: vlan100
            2:
                name: "host2"
                description: "host2 network namespace"
                native_vlan: vlan200
```

IVR works fine and all hosts can ping. Now if we move host2 from port 2 to port 3, update the configuration to reflect this and reload faucet we will find the route to 10.0.1.1/32 is still pointing to port 2 which no longer exists and we have to wait until this timeouts for this host to rejoin the network.
