### ISSUE TITLE
New bgp style config causes routing issues

### ISSUE THREAD

**Issue by gizmoguy** [faucetsdn/faucet#2875]
So this config seems to work fine, every host on my network can route to every other host:

```
routers:
    vlan-router:
        vlans: [reannz-l3, redcables-l3, events-l3, ggc-l3, scale-test-l3]
        bgp:
            vlan: reannz-l3
            connect_mode: passive
            routerid: '127.0.0.2'
            server_addresses: ['127.0.0.2', '::1']
            port: 9179
            as: 134227
            neighbor_addresses: ['127.0.0.1', '::1']
            neighbor_as: 134227
```

If we instead separate BGP into a separate router like below, we will notice that we are no longer able to route between all hosts on all VLANs (IPv6 seems to be more seriously impacted than IPv4):

```
routers:
    vlan-router:
        vlans: [reannz-l3, redcables-l3, events-l3, ggc-l3, scale-test-l3]
    bgp-router:
        bgp:
            vlan: reannz-l3
            connect_mode: passive
            routerid: '127.0.0.2'
            server_addresses: ['127.0.0.2', '::1']
            port: 9179
            as: 134227
            neighbor_addresses: ['127.0.0.1', '::1']
            neighbor_as: 134227
```
