### ISSUE TITLE
FAUCET should ignore BGP routes with nexthop == BGP neighbor address

### ISSUE THREAD

**Issue by gizmoguy** [faucetsdn/faucet#2878]
Take the following BGP configuration:

```
routers:
    vlan-router:
        vlans: [internet, office]
    bgp-router:
        bgp:
            vlan: internet
            connect_mode: passive
            routerid: '127.0.0.2'
            server_addresses: ['127.0.0.2', '::1']
            port: 9179
            as: 134227
            neighbor_addresses: ['127.0.0.1', '::1']
            neighbor_as: 134227

vlans:
    internet:
        name: "reannz-l3"
        description: "reannz peering vlan"
        vid: 2406
    office:
        vid: 250
        faucet_vips: ['163.7.137.254/24']
        routes:
            - route:
                ip_dst: '2404:138:4011::/64'
                ip_gw: '2404:138:4011:3e8::fffd'
            - route:
                ip_dst: '163.7.136.0/25'
                ip_gw: '163.7.137.252'
```

Faucet will generate a nonsensical route that looks like:

```
Mar 21 13:32:26 faucet INFO     Re-adding 163.7.136.0/23 via 127.0.0.1
Mar 21 13:32:26 faucet.valve ERROR    DPID 70 (0x46) ovs-redcables Cannot resolve destination VLAN for gateway 127.0.0.1 in router vlan-router (not in global router?)
```
