### ISSUE TITLE
Routing on faucet stacks can miss installing some flows

### ISSUE THREAD

**Issue by gizmoguy** [faucetsdn/faucet#3149]
[Reported by: Tim Weippert]

Take the following config:

```
vlans:
    office:
        vid: 100
        description: "office network"
        faucet_mac: "0e:00:00:00:10:01"
        faucet_vips: ['10.0.100.254/24', '2001:100::1/64', 'fe80::c00:00ff:fe00:1001/64']
    guest:
        vid: 200
        description: "guest network"
        faucet_mac: "0e:00:00:00:20:01"
        faucet_vips: ['10.0.200.254/24', '2001:200::1/64', 'fe80::c00:00ff:fe00:2001/64']

routers:
    router-office-guest:
        vlans: [office, guest]

dps:
    OF1:
        dp_id: 0x1
        description: "OF1"
        hardware: "Open vSwitch"
        stack:
            priority: 1
        lldp_beacon:
            send_interval: 5
            max_per_interval: 5

        interfaces:
            1:
                name: "host1"
                description: "host1 container"
                native_vlan: office
            2:
                name: "host2"
                description: "host2 container"
                native_vlan: office
            3:
                name: "guest1"
                description: "guest1 container"
                native_vlan: guest
            5:
                stack: { dp: OF2, port: 5 }

    OF2:
        dp_id: 0x2
        description: "OF2"
        hardware: "Open vSwitch"
        lldp_beacon:
            send_interval: 5
            max_per_interval: 5
        interfaces:
            1:
                name: "pi"
                description: "raspberry pi"
                native_vlan: office
            5:
                name: "trunk"
                description: "VLAN trunk to sw1"
                stack: { dp: OF1, port: 5 }
```

Ping (v4 & v6) between hosts on the same OVS works fine, also between VLANs
(faucet routed). But from DP1 (OF1) to DP2 (OF2) between VLANs it doesn't
work actually. 

It seems that on OF2 the needed table 2 Openflow Entries aren't installed:

```
[weiti@arch01 faucet-stack-routing (master)]$ ofctl13 dump-flows OF2 table=2
 cookie=0x5adc15c0, duration=571.557s, table=2, n_packets=0, n_bytes=0, priority=12320,ip,dl_vlan=100,nw_dst=10.0.100.254 actions=goto_table:4
 cookie=0x5adc15c0, duration=560.579s, table=2, n_packets=0, n_bytes=0, priority=12320,ip,dl_vlan=100,nw_dst=10.0.100.20 actions=set_field:4196->vlan_vid,set_field:0e:00:00:00:10:01->eth_src,set_field:ee:94:34:01:71:60->eth_dst,dec_ttl,goto_table:5
 cookie=0x5adc15c0, duration=557.927s, table=2, n_packets=0, n_bytes=0, priority=12320,ip,dl_vlan=100,nw_dst=10.0.100.100 actions=set_field:4196->vlan_vid,set_field:0e:00:00:00:10:01->eth_src,set_field:ba:2b:11:92:73:e6->eth_dst,dec_ttl,goto_table:5
 cookie=0x5adc15c0, duration=357.531s, table=2, n_packets=0, n_bytes=0, priority=12320,ip,dl_vlan=100,nw_dst=10.0.100.10 actions=set_field:4196->vlan_vid,set_field:0e:00:00:00:10:01->eth_src,set_field:6e:fd:22:b2:21:01->eth_dst,dec_ttl,goto_table:5
 cookie=0x5adc15c0, duration=571.557s, table=2, n_packets=0, n_bytes=0, priority=12312,ip,dl_vlan=100,nw_dst=10.0.100.0/24 actions=goto_table:4
 cookie=0x5adc15c0, duration=571.474s, table=2, n_packets=0, n_bytes=0, priority=0 actions=drop
```

```
[weiti@arch01 faucet-stack-routing (master)]$ ofctl13 dump-flows OF1 table=2
 cookie=0x5adc15c0, duration=578.312s, table=2, n_packets=0, n_bytes=0, priority=12320,ip,dl_vlan=100,nw_dst=10.0.100.254 actions=goto_table:4
 cookie=0x5adc15c0, duration=578.312s, table=2, n_packets=3, n_bytes=294, priority=12320,ip,dl_vlan=200,nw_dst=10.0.200.254 actions=goto_table:4
 cookie=0x5adc15c0, duration=567.426s, table=2, n_packets=0, n_bytes=0, priority=12320,ip,dl_vlan=100,nw_dst=10.0.100.20 actions=set_field:4196->vlan_vid,set_field:0e:00:00:00:10:01->eth_src,set_field:ee:94:34:01:71:60->eth_dst,dec_ttl,goto_table:5
 cookie=0x5adc15c0, duration=567.426s, table=2, n_packets=2, n_bytes=196, priority=12320,ip,dl_vlan=200,nw_dst=10.0.100.20 actions=set_field:4196->vlan_vid,set_field:0e:00:00:00:10:01->eth_src,set_field:ee:94:34:01:71:60->eth_dst,dec_ttl,goto_table:5
 cookie=0x5adc15c0, duration=564.773s, table=2, n_packets=0, n_bytes=0, priority=12320,ip,dl_vlan=100,nw_dst=10.0.100.100 actions=set_field:4196->vlan_vid,set_field:0e:00:00:00:10:01->eth_src,set_field:ba:2b:11:92:73:e6->eth_dst,dec_ttl,goto_table:5
 cookie=0x5adc15c0, duration=564.773s, table=2, n_packets=5, n_bytes=490, priority=12320,ip,dl_vlan=200,nw_dst=10.0.100.100 actions=set_field:4196->vlan_vid,set_field:0e:00:00:00:10:01->eth_src,set_field:ba:2b:11:92:73:e6->eth_dst,dec_ttl,goto_table:5
 cookie=0x5adc15c0, duration=507.460s, table=2, n_packets=13, n_bytes=1274, priority=12320,ip,dl_vlan=100,nw_dst=10.0.200.10 actions=set_field:4296->vlan_vid,set_field:0e:00:00:00:20:01->eth_src,set_field:52:a7:d5:f5:c5:17->eth_dst,dec_ttl,goto_table:5
 cookie=0x5adc15c0, duration=507.460s, table=2, n_packets=0, n_bytes=0, priority=12320,ip,dl_vlan=200,nw_dst=10.0.200.10 actions=set_field:4296->vlan_vid,set_field:0e:00:00:00:20:01->eth_src,set_field:52:a7:d5:f5:c5:17->eth_dst,dec_ttl,goto_table:5
 cookie=0x5adc15c0, duration=364.376s, table=2, n_packets=0, n_bytes=0, priority=12320,ip,dl_vlan=100,nw_dst=10.0.100.10 actions=set_field:4196->vlan_vid,set_field:0e:00:00:00:10:01->eth_src,set_field:6e:fd:22:b2:21:01->eth_dst,dec_ttl,goto_table:5
 cookie=0x5adc15c0, duration=364.376s, table=2, n_packets=11, n_bytes=1078, priority=12320,ip,dl_vlan=200,nw_dst=10.0.100.10 actions=set_field:4196->vlan_vid,set_field:0e:00:00:00:10:01->eth_src,set_field:6e:fd:22:b2:21:01->eth_dst,dec_ttl,goto_table:5
 cookie=0x5adc15c0, duration=578.310s, table=2, n_packets=0, n_bytes=0, priority=12312,ip,dl_vlan=100,nw_dst=10.0.100.0/24 actions=goto_table:4
 cookie=0x5adc15c0, duration=578.310s, table=2, n_packets=0, n_bytes=0, priority=12312,ip,dl_vlan=200,nw_dst=10.0.100.0/24 actions=goto_table:4
 cookie=0x5adc15c0, duration=578.310s, table=2, n_packets=0, n_bytes=0, priority=12312,ip,dl_vlan=100,nw_dst=10.0.200.0/24 actions=goto_table:4
 cookie=0x5adc15c0, duration=578.310s, table=2, n_packets=0, n_bytes=0, priority=12312,ip,dl_vlan=200,nw_dst=10.0.200.0/24 actions=goto_table:4
 cookie=0x5adc15c0, duration=578.305s, table=2, n_packets=0, n_bytes=0, priority=0 actions=drop
```

The packet seems to get dropped on OF2 table 2, as there is no vlan 200 informations or at least nw_dst=10.0.200.0/24 action.
