### ISSUE TITLE
no VLANs referenced by interfaces

### ISSUE THREAD

**Issue by gizmoguy** [faucetsdn/faucet#3272]
Take a traditional spine and leaf architecture:

![IMG_20191003_144512](https://user-images.githubusercontent.com/383287/66093376-8b159200-e5ec-11e9-9854-f3c8e879b342.jpg)

Defined by the following config file:

```
vlans:
    hosts:
        vid: 100
dps:
    br1:
        dp_id: 0x1
        hardware: "Open vSwitch"
        stack:
            priority: 1
        interfaces:
            1:
                description: "br1 stack link to br3"
                stack:
                    dp: sw3
                    port: 2
            2:
                description: "br1 stack link to br4"
                stack:
                    dp: sw4
                    port: 3

    br2:
        dp_id: 0x2
        hardware: "Open vSwitch"
        stack:
            priority: 1
        interfaces:
            1:
                description: "br2 stack link to br4"
                stack:
                   dp: sw4
                   port: 2
            2:
                description: "br2 stack link to br3"
                stack:
                    dp: sw3
                    port: 3
    br3:
        dp_id: 0x3
        hardware: "Open vSwitch"
        interfaces:
            1:
                description: "host1 network namespace"
                native_vlan: hosts
            2:
                description: "br3 stack link to br1"
                stack:
                   dp: sw1
                   port: 1
            3:
                description: "br3 stack link to br2"
                stack:
                    dp: sw2
                    port: 2
    br4:
        dp_id: 0x4
        hardware: "Open vSwitch"
        interfaces:
            1:
                description: "host2 network namespace"
                native_vlan: hosts
            2:
                description: "br4 stack link to br2"
                stack:
                   dp: sw2
                   port: 1
            3:
                description: "br4 stack link to br1"
                stack:
                    dp: sw1
                    port: 2
```

We get a config error, because the root switches have no vlans expressed:

```
brad@faucet-sandbox:~$ check_faucet_config /etc/faucet/faucet.yaml 
[InvalidConfigError('no VLANs referenced by interfaces in sw1',)]

```

What we would expect is that vlans expressed on br3/br4 are automatically expressed on br1/br2 without having to manually define them.
