### ISSUE TITLE
Can't configure same tunnel ACL on multiple ports

### ISSUE THREAD

**Issue by gizmoguy** [faucetsdn/faucet#3280]
If we take a simple faucet stack topology of two switches connected to each other with a tunnel ACL that sends packets from one switch to the other:
```

acls:
    tunnel-acl:
        - rule:
            actions:
                output:
                    tunnel:
                        type: 'vlan'
                        tunnel_id: 301
                        dp: br1
                        port: 2
vlans:
    hosts:
       vid: 100
dps:
    br1:
        dp_id: 0x1
        hardware: "Open vSwitch"
        stack:
            priority: 1
        interfaces:
            1:
                description: "tap"
                output_only: True
            2:
                description: "br1 stack link to br2"
                stack:
                    dp: br2
                    port: 3
            3:
                description: "dummy"
                native_vlan: hosts
    br2:
        dp_id: 0x2
        hardware: "Open vSwitch"
        interfaces:
            1:
                description: "host1 network namespace"
                native_vlan: hosts
                acl_in: tunnel-acl
            2:
                description: "host2 network namespace"
                native_vlan: hosts
            3:
                description: "br2 stack link to br1"
                stack:
                    dp: br1
                    port: 2
```

If we run check_faucet_config on this it passes fine. If we were to add "acl_in: tunnel-acl" to port 2 we would get this non-obvious error:

```
brad@faucet-sandbox:~$ check_faucet_config /etc/faucet/faucet.yaml 
[InvalidConfigError("Conf object must be type <class 'dict'> not <class 'int'>",)]
```
