### ISSUE TITLE
Dynamic named tunnel VLANs

### ISSUE THREAD

**Issue by cglewis** [faucetsdn/faucet#3314]
Currently it is required to create a tunnel with an unused VLAN. That's great, as it's unlikely a network is going to have completely saturated all VLANs.  However, it presents the problem of having to specify one to reserve manually and hope that the operator or application didn't use a VLAN already in use.

Since Faucet will have full knowledge of the VLANs already in use, I propose using unqiue names for the IDs and behind the scenes Faucet picks an unused VLAN, which may change upon config reload (since reloading could introduce new VLANs).

Currently this looks like where the VLAN number is specified:
```
acls:
  tunnel-to-host1:
    - rule:
      action:
      output:
        tunnel:
          type: 'vlan'
          tunnel_id: 901
          dp: x230
          port: 1
        allow: 1
```

Or this where the name of the VLAN is specified and defined:
```
acls:
  tunnel-to-host1:
    - rule:
      action:
      output:
        tunnel:
          type: 'vlan'
          tunnel_id: foo
          dp: x230
          port: 1
        allow: 1
vlans:
  foo:
    vid: 100
```

What I'm proposing as an option (or replacement, maybe) would be to be able to do this (or something like this):
```
acls:
  tunnel-to-host1:
    - rule:
      action:
      output:
        tunnel:
          type: 'vlan'
          tunnel_id: foo
          dp: x230
          port: 1
        allow: 1
```
And behind the scenes Faucet would pick a `vid` not in use.
