### ISSUE TITLE
stack transit switches do not support L2 traffic

### ISSUE THREAD

**Issue by mwutzke** [faucetsdn/faucet#3383]
Even after #3272, I am still unable to get L2 transit traffic to flow, without adding a dummy interface to the transit switch.

The reproduction (Faucet 1.9.26) uses a topology similar to that shown in the 'tuneling over a stack' tutorial, with the tunnel removed, and host1 and host2 in the same VLAN. The faucet.yaml for this is:

```
vlans:
    hosts:
       vid: 101
dps:
    br0:
        dp_id: 0x1
        hardware: "Open vSwitch"
        stack:
            priority: 1
        interfaces:
            1:
                native_vlan: hosts
            2:
                stack:
                    dp: br1
                    port: 1
    br1:
        dp_id: 0x2
        hardware: "Open vSwitch"
        interfaces:
            1:
                stack:
                   dp: br0
                   port: 2
            2:
                stack:
                    dp: br2
                    port: 2
    br2:
        dp_id: 0x3
        hardware: "Open vSwitch"
        interfaces:
            1:
                native_vlan: hosts
            2:
                stack:
                    dp: br1
                    port: 2
```

With this config, the OF rules for table1 on br1 only show the following:
```
 cookie=0x5adc15c0, duration=34.623s, table=0, n_packets=0, n_bytes=0, priority=0 actions=drop
 cookie=0x5adc15c0, duration=34.623s, table=1, n_packets=0, n_bytes=0, priority=20490,dl_type=0x9000 actions=drop
 cookie=0x5adc15c0, duration=34.623s, table=1, n_packets=0, n_bytes=0, priority=20480,dl_src=ff:ff:ff:ff:ff:ff actions=drop
 cookie=0x5adc15c0, duration=34.623s, table=1, n_packets=0, n_bytes=0, priority=0 actions=resubmit(,2)
```
and all traffic for vlan101 via this transit switch, gets dropped by the table3 'drop' rule
