### ISSUE TITLE
stack tunnelled traffic and 'allow:true' doesn't produce expected results

### ISSUE THREAD

**Issue by mwutzke** [faucetsdn/faucet#3389]
When using a tunnel ACL (with allow:true) to tunnel traffic to a to a remote egress switch, it appears that the expected allow:true processing for certain egress traffic flows does not occur.

Using a network configuration like the following

```
host12 -- sw1 ==== sw3 -- host31
           |
           |
      host199 (tunnel egress)
```

with the following faucet.yaml against 2 OVS bridge instances:

```
acls:
  tunnel-udp:
    - rule:
        dl_type: 0x0800         # IPv4
        nw_proto: 17            # UDP
        actions:
          output:
            tunnel:
              type: 'vlan'
              tunnel_id: 4010
              dp: sw1
              port: 99
          allow: true


vlans:
  home:
    vid: 100

dps:
  sw1:
    dp_id: 0x1
    hardware: "Open vSwitch"
    stack:
      priority: 1
    interfaces:
      1:
        native_vlan: home
      10:
        stack:
          dp: sw3
          port: 10
      99:
        description: monitoring port
        output_only: true
  sw3:
    dp_id: 0x3
    hardware: "Open vSwitch"
    interfaces:
      1:
        native_vlan: home
        acls_in: [tunnel-udp]
      10:
        stack:
          dp: sw1
          port: 10
```

Injecting L2 flooded UDP traffic on sw3/1, this traffic gets tunnelled to sw1/99, as expected. But, the traffic is not L2 forwarded to the other ports in the vlan on remote DPs - eg sw1/1, as I was expecting given the 'allow:true' in the ACL.

But, by removing the 'acls_in' stanza from sw3/1, this allows the ingress UDP traffic on sw3/1 to be L2 forwarded to sw1/1 correctly.

With the original config, I see the following OF rules in sw3:

```
vagrant@faucet-u1804:~$ sudo ovs-ofctl dump-flows br3
 cookie=0x5adc15c0, duration=369.185s, table=0, n_packets=38, n_bytes=3720, priority=20480,in_port="l-br3_10-br1_10" actions=resubmit(,1)
 cookie=0x5adc15c0, duration=364.242s, table=0, n_packets=24, n_bytes=1008, priority=20480,udp,in_port="veth-host31" actions=mod_vlan_vid:4010,output:"l-br3_10-br1_10",resubmit(,1)
...
 cookie=0x5adc15c0, duration=369.180s, table=1, n_packets=0, n_bytes=0, priority=9000,in_port="veth-host31",vlan_tci=0x0000/0x1fff actions=mod_vlan_vid:100,resubmit(,2)
 cookie=0x5adc15c0, duration=369.174s, table=1, n_packets=24, n_bytes=1008, priority=0 actions=drop
...
 cookie=0x5adc15c0, duration=364.229s, table=2, n_packets=0, n_bytes=0, priority=4096,dl_vlan=100 actions=CONTROLLER:96,resubmit(,3)
 cookie=0x5adc15c0, duration=364.229s, table=2, n_packets=0, n_bytes=0, priority=4096,dl_vlan=4010 actions=CONTROLLER:96,resubmit(,3)
...
 cookie=0x5adc15c0, duration=369.175s, table=3, n_packets=0, n_bytes=0, priority=0 actions=resubmit(,4)
...
 cookie=0x5adc15c0, duration=364.242s, table=4, n_packets=0, n_bytes=0, priority=8240,dl_vlan=100,dl_dst=ff:ff:ff:ff:ff:ff actions=output:"l-br3_10-br1_10",strip_vlan,output:"veth-host31"
```

While, without the tunnel ACL applied, sw3 shows the following flows, which works for UDP traffic stream:

```
vagrant@faucet-u1804:~$ sudo ovs-ofctl dump-flows br3
 cookie=0x5adc15c0, duration=26.521s, table=0, n_packets=0, n_bytes=0, priority=9001,in_port="l-br3_10-br1_10",vlan_tci=0x0000/0x1fff actions=drop
 cookie=0x5adc15c0, duration=26.519s, table=0, n_packets=15, n_bytes=630, priority=9000,in_port="veth-host31",vlan_tci=0x0000/0x1fff actions=mod_vlan_vid:100,resubmit(,2)
...
 cookie=0x5adc15c0, duration=16.188s, table=2, n_packets=14, n_bytes=588, hard_timeout=282, priority=8191,in_port="veth-host31",dl_vlan=100,dl_src=4e:9f:83:7e:7d:ee actions=resubmit(,3)
 cookie=0x5adc15c0, duration=25.525s, table=2, n_packets=1, n_bytes=42, priority=4096,dl_vlan=100 actions=CONTROLLER:96,resubmit(,3)
 cookie=0x5adc15c0, duration=25.525s, table=2, n_packets=0, n_bytes=0, priority=4096,dl_vlan=4010 actions=CONTROLLER:96,resubmit(,3)
...
 cookie=0x5adc15c0, duration=26.518s, table=3, n_packets=15, n_bytes=630, priority=0 actions=resubmit(,4)
...
 cookie=0x5adc15c0, duration=25.536s, table=4, n_packets=15, n_bytes=630, priority=8240,dl_vlan=100,dl_dst=ff:ff:ff:ff:ff:ff actions=output:"l-br3_10-br1_10",strip_vlan,output:"veth-host31"
```

Looking at the failing flows again, I suspect the issue is with this flow:

>  cookie=0x5adc15c0, duration=364.242s, table=0, n_packets=24, n_bytes=1008, priority=20480,udp,in_port="veth-host31" actions=mod_vlan_vid:4010,output:"l-br3_10-br1_10",resubmit(,1)

interacting with this flow:

>  cookie=0x5adc15c0, duration=369.180s, table=1, n_packets=0, n_bytes=0, priority=9000,in_port="veth-host31",vlan_tci=0x0000/0x1fff actions=mod_vlan_vid:100,resubmit(,2)

I believe the mod_vlan_vid:4010 causes the vlan_tci=0x0000/0x1fff match to fail, so then:

> cookie=0x5adc15c0, duration=364.242s, table=4, n_packets=0, n_bytes=0, priority=8240,dl_vlan=100,dl_dst=ff:ff:ff:ff:ff:ff actions=output:"l-br3_10-br1_10",strip_vlan,output:"veth-host31"

doesn't get matched / executed either.
