### ISSUE TITLE
Faucet ACL ambiguity & allowing badly defined ACLs

### ISSUE THREAD

**Issue by mab68** [faucetsdn/faucet#3468]
Currently Faucet happily accepts ACLs of the following form:
```
acls:
    funky_acl:
        - rule:
            dl_vlan: 100
            actions:
                allow: 1
                output:
                    vlan_vid: 5
                    port: 2
                    pop_vlans: 1
                    ports: [3]
                    vlan_vids: [6, 7]
```
Which compiles to the following flowrule:
```
in_port="veth-host1",dl_vlan=100 actions=strip_vlan,mod_vlan_vid:5,output:"veth-host2",output:"veth-host3",resubmit(,1)
```

There are two problems with this
- Faucet does not accept duplicate keys but does accept the different forms of the same action ie: vlan_vid & vlan_vids.
- Faucet specifically applies actions based on some non-sequential order. For example VLAN header based ACLs are always applied first.

I would personally expect for ACL actions to be applied in order, having Faucet quietly decide to move actions around might create some problems for the user. I also think there should not be a problem with having duplicate keys in an output action.

**Comment by gizmoguy** [comment]
So I think the obvious answer to your first problem. We should only ever allow one of vlan_vid/vlan_vids and port/ports. We should have throw a config exception at runtime informing the user and not start up.

I think the second problem will require some more thought. Expressing order in a consistent way in YAML can be a difficult problem.

**Comment by cglewis** [comment]
@gizmoguy Just to chime in here as well, I agree with both of your points.

The order is especially difficult because guaranteeing it's hand written by a user who uses a specific order is one thing, but systems that rewrite it don't necessarily make that same guarantee, which is often dependent on the implementation of the library being used. Specifically pyyaml does this, which Poseidon uses and it definitely doesn't guarantee order. I would have to rethink that as well if this moved to order dependent.

On a more practical note, it seems like requiring order would add unnecessary details the end user would need to know. I agree it would allow for more flexibility and control for an advanced user, but the tradeoff is that beginners now have to understand flow order really really well to get expected outcomes.

**Comment by mab68** [comment]
The actions have to be applied in some ordering, so no matter what a user will need to know what Faucet builds (which may or may not match a users expectation). Faucet currently applies the actions in the following order: VLANs headers (with its own order of _pop_vlans_ followed by _vlan_vids_, _swap_vid_ and _vlan_vids_ which are mutually exclusive),  _set_fields_ and then ports. At the very least we could update the documentation for this.

I can't think of any way to get the actions built in order using the current format, but using a sequence should be possible. Unfortunately this does require a config change.
EG: 
```
acls:
    funky_acl:
        - rule:
            dl_vlan: 100
            actions:
                output:
                    - port: 2
                    - pop_vlans: 1
                    - port: 3
```
