### ISSUE TITLE
BGP routing gets confused when there are multiple DPs

### ISSUE THREAD

**Issue by gizmoguy** [faucetsdn/faucet#3518]
Take the following config:

```
vlans:
    office:
        vid: 100
        description: "office network"
        faucet_mac: "0e:00:00:00:10:01"
        faucet_vips: ['192.168.0.254/24']
    guest:
        vid: 200
        description: "guest network"
        faucet_mac: "0e:00:00:00:20:01"
        faucet_vips: ['20.0.0.254/8']
routers:
    router-bgp:
        bgp:
            vlan: office
            connect_mode: "passive"
            as: 65000
            port: 9179
            routerid: '192.168.0.252'
            server_addresses: ["127.0.0.1"]
            neighbor_addresses: ["127.0.0.1"]
            neighbor_as: 65000

dps:
      sw3:
             dp_id: 0x3
             hardware: "Open vSwitch"
             interfaces:
                 1:
                     name: "OVS1-CONN"
                     description: "ovs1 connection"
                     native_vlan: guest
      swdev:
             dp_id: 0xf
             hardware: "Open vSwitch"
             interfaces:
                 1:
                     name: "client 1"
                     native_vlan: "office"
                 99:
                     name: "Faucet "
                     native_vlan: office
```

This doesn't work for an unknown reason, despite the "office" vlan only being enabled on a single DP:

`[InvalidConfigError('router router-bgp configured but not used by any DP',)]`

When IVR is introduced things get even more complicated:

```
vlans:
    office:
        vid: 100
        description: "office network"
        faucet_mac: "0e:00:00:00:10:01"
        faucet_vips: ['192.168.0.254/24']
    guest:
        vid: 200
        description: "guest network"
        faucet_mac: "0e:00:00:00:20:01"
        faucet_vips: ['20.0.0.254/8']
routers:
    router-office-guest:
        vlans: [office, guest]
    router-bgp:
        bgp:
            vlan: office
            connect_mode: "passive"
            as: 65000
            port: 9179
            routerid: '192.168.0.252'
            server_addresses: ["127.0.0.1"]
            neighbor_addresses: ["127.0.0.1"]
            neighbor_as: 65000

dps:
      sw3:
             dp_id: 0x3
             hardware: "Open vSwitch"
             interfaces:
                 1:
                     name: "OVS1-CONN"
                     description: "ovs1 connection"
                     native_vlan: guest
      swdev:
             dp_id: 0xf
             hardware: "Open vSwitch"
             interfaces:
                 1:
                     name: "client 1"
                     native_vlan: "office"
                 2:
                     name: "client 2"
                     native_vlan: "guest"
                 3:
                     name: "client 3"
                     native_vlan: guest
                 99:
                     name: "Faucet "
                     native_vlan: office
```

This errors out with:

[InvalidConfigError('DPs (3, 15) sharing a BGP speaker VLAN (100) is unsupported',)]
