### ISSUE TITLE
Unable to add meters for rate limiting

### ISSUE THREAD

**Issue by Yawndy** [faucetsdn/faucet#3968]
I am trying to add a meter so I can implement rate-limiting for my Faucet SDN solution, but I always get this error when running check_faucet_config, "AttributeError: 'str' object has no attribute 'get'". 

Here is my current config:
```
meters:
        block-dos:
                meter_id: 100
                entry:
                        flags: PKTPS
                        bands:
                                rate: 1
```

Is anybody able to tell me what I'm doing wrong here? Any help is GREATLY appreciated!

**Comment by gizmoguy** [comment]
I think bands needs to be a list, so try this:

```
meters:
        block-dos:
                meter_id: 100
                entry:
                        flags: PKTPS
                        bands:
                            - rate: 1
```
